#include "rv_declarations.h"

/*** global declarations of both sides: ***/

/*** global declarations side 0: ***/
int  rvs0_checkInput(int  n);
int  chk0_f(int  n);
int  rvs0_main();
int  rvs0_checkInput(int  n);
unsigned char  rvs0_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
unsigned char  rvs0_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_2);

/*** global declarations side 1: ***/
int  rvs1_checkInput(int  n);
int  chk1_f(int  n);
int  rvs1_main();
int  rvs1_checkInput(int  n);
unsigned char  rvs1_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
unsigned char  rvs1_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_3);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  chk0_f(int  n)
{
  int  rvretval = 0;

  if (rvs0_checkInput(n))
  {
    return 0;
  }

  int  i;
  int  sum = 0;
  {
    i = 1;
    rvs0_Loop_f_for1(n,&i,&sum,&rvretval);
  }

  return sum;
}


/*** Functions side 1: ***/
int  chk1_f(int  n)
{
  int  rvretval = 0;

  if (rvs1_checkInput(n))
  {
    return 0;
  }

  int  sum = 0;
  {
    int  i = 1;

    {
      rvs1_Loop_f_for1(n,&i,&sum,&rvretval);
    }

  }

  return sum;
}


/* Implementations of the uninterpreted functions: */
#define rv_UF_K_Loop_f_for1 5
//Recording arrays for local parameter input
int  rvt_token_Loop_f_for1_n[rv_UF_K_Loop_f_for1];
int  rvt_token_Loop_f_for1_rvp_i[rv_UF_K_Loop_f_for1];
int  rvt_token_Loop_f_for1_rvp_sum[rv_UF_K_Loop_f_for1];
int  rvt_token_Loop_f_for1_rvp_rvretval[rv_UF_K_Loop_f_for1];

//Recording arrays for global input

//Output arrays for local input
int  rvt_token_Loop_f_for1_n_output[rv_UF_K_Loop_f_for1];

int  rvt_token_Loop_f_for1_rvp_i_output[rv_UF_K_Loop_f_for1];

int  rvt_token_Loop_f_for1_rvp_sum_output[rv_UF_K_Loop_f_for1];

int  rvt_token_Loop_f_for1_rvp_rvretval_output[rv_UF_K_Loop_f_for1];


//Output arrays for global input

//Output array for function output
unsigned char  rvt_token_Loop_f_for1_retval_output[rv_UF_K_Loop_f_for1];

int  rvt_token_Loop_f_for1_call_mark_array0[rv_UF_K_Loop_f_for1];
int  rvt_token_Loop_f_for1_call_mark_array1[rv_UF_K_Loop_f_for1];
int  rvt_token_Loop_f_for1_count;
_Bool  rvt_token_Loop_f_for1_first_call_to_uf_flag;

 /*** uninterpreted function side 0: ***/ 
unsigned char  rvs0_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval)
{
  unsigned char  retval;

 /* Zeroing both mark arrays and count variable for unitrv mutual termination check */
  /* save values of input arguments: */
	rvt_token_Loop_f_for1_n[rvt_token_Loop_f_for1_count] = n;
	rvt_token_Loop_f_for1_rvp_i[rvt_token_Loop_f_for1_count] = *rvp_i;
	rvt_token_Loop_f_for1_rvp_sum[rvt_token_Loop_f_for1_count] = *rvp_sum;
  /* save values of input globals: */

  /* generate and save values of output arguments and globals: */
  rvt_token_Loop_f_for1_rvp_i_output[rvt_token_Loop_f_for1_count] = *rvp_i = (int )nondet_long();	/* Generated by:  RVReUfGen::gen_unitrv_side0_uf(615)/ RVGen::protect_pointer [op=2](620)(386)(267)/ c:\newrvt\rv_temps.cpp:420*/
  rvt_token_Loop_f_for1_rvp_sum_output[rvt_token_Loop_f_for1_count] = *rvp_sum = (int )nondet_long();	/* Generated by:  RVReUfGen::gen_unitrv_side0_uf(615)/ RVGen::protect_pointer [op=2](620)(386)(267)(615)/ RVGen::protect_pointer [op=2](620)(386)(267)/ c:\newrvt\rv_temps.cpp:420*/

  /* generate and save value for the functino output : */
  rvt_token_Loop_f_for1_retval_output[rvt_token_Loop_f_for1_count] = retval = (unsigned char )nondet_int();	/* Generated by:  RVReUfGen::gen_unitrv_side0_uf(615)/ RVGen::protect_pointer [op=2](620)(386)(267)(615)/ RVGen::protect_pointer [op=2](620)(386)(267)(615)(620)(386)(267)/ c:\newrvt\rv_temps.cpp:420*/
	rvt_token_Loop_f_for1_call_mark_array0[rvt_token_Loop_f_for1_count] = 1;
	rvt_token_Loop_f_for1_count++;
  return retval;
}


/*** uninterpreted function side 1: ***/ 
unsigned char  rvs1_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval)
{
  unsigned char  retval;

  _Bool found = 0;
  _Bool equal = 1;
  int found_ind = -1;
  int rv_uf_ind = rvt_token_Loop_f_for1_count-1;
  for(; rv_uf_ind >= 0; rv_uf_ind--) {
		equal = equal && n == rvt_token_Loop_f_for1_n[rv_uf_ind];
		equal = equal && *rvp_i == rvt_token_Loop_f_for1_rvp_i[rv_uf_ind];
		equal = equal && *rvp_sum == rvt_token_Loop_f_for1_rvp_sum[rv_uf_ind];
    if( equal ) { 
      found = 1;
      found_ind = rv_uf_ind;
		rvt_token_Loop_f_for1_call_mark_array1[rv_uf_ind] = 1;
    }
		equal = 1;
  }

  if( found ) /* input values were found among the saved values */
  {
   /* Sides 0 and 1 are partially equivalent.
    * Returning the results of side 0: */
	*rvp_i = rvt_token_Loop_f_for1_rvp_i_output[rv_uf_ind];
	*rvp_sum = rvt_token_Loop_f_for1_rvp_sum_output[rv_uf_ind];
  retval = rvt_token_Loop_f_for1_retval_output[rv_uf_ind];	/* Generated by:  RVReUfGen::gen_unitrv_input_found_case(615)(620)(386)(290)/ c:\newrvt\rv_temps.cpp:362*/

  } else {

    /* Assert reach-equivalence: side 0 and 1 inputs are equal.*/
    assert( 0 );

  }

  return retval;
}

void rvt_token_initialize_mutual_termination_tokens_Loop_f_for1(){
	int rvt_token_i = 0;
		for (rvt_token_i = 0 ; rvt_token_i < rv_UF_K_Loop_f_for1 ; rvt_token_i++){
			rvt_token_Loop_f_for1_call_mark_array0[rvt_token_i] = 0;
			rvt_token_Loop_f_for1_call_mark_array1[rvt_token_i] = 0;
		}
		rvt_token_Loop_f_for1_count = 0;
		rvt_token_Loop_f_for1_first_call_to_uf_flag = 0;

}
#define rv_UF_K_checkInput 5
//Recording arrays for local parameter input
int  rvt_token_checkInput_n[rv_UF_K_checkInput];

//Recording arrays for global input

//Output arrays for local input
int  rvt_token_checkInput_n_output[rv_UF_K_checkInput];


//Output arrays for global input

//Output array for function output
int  rvt_token_checkInput_retval_output[rv_UF_K_checkInput];

int  rvt_token_checkInput_call_mark_array0[rv_UF_K_checkInput];
int  rvt_token_checkInput_call_mark_array1[rv_UF_K_checkInput];
int  rvt_token_checkInput_count;
_Bool  rvt_token_checkInput_first_call_to_uf_flag;

 /*** uninterpreted function side 0: ***/ 
int  rvs0_checkInput(int  n)
{
  int  retval;

 /* Zeroing both mark arrays and count variable for unitrv mutual termination check */
  /* save values of input arguments: */
	rvt_token_checkInput_n[rvt_token_checkInput_count] = n;
  /* save values of input globals: */

  /* generate and save values of output arguments and globals: */

  /* generate and save value for the functino output : */
  rvt_token_checkInput_retval_output[rvt_token_checkInput_count] = retval = (int )nondet_long();	/* Generated by:  RVReUfGen::gen_unitrv_side0_uf(615)(620)(386)(267)/ c:\newrvt\rv_temps.cpp:420*/
	rvt_token_checkInput_call_mark_array0[rvt_token_checkInput_count] = 1;
	rvt_token_checkInput_count++;
  return retval;
}


/*** uninterpreted function side 1: ***/ 
int  rvs1_checkInput(int  n)
{
  int  retval;

  _Bool found = 0;
  _Bool equal = 1;
  int found_ind = -1;
  int rv_uf_ind = rvt_token_checkInput_count-1;
  for(; rv_uf_ind >= 0; rv_uf_ind--) {
		equal = equal && n == rvt_token_checkInput_n[rv_uf_ind];
    if( equal ) { 
      found = 1;
      found_ind = rv_uf_ind;
		rvt_token_checkInput_call_mark_array1[rv_uf_ind] = 1;
    }
		equal = 1;
  }

  if( found ) /* input values were found among the saved values */
  {
   /* Sides 0 and 1 are partially equivalent.
    * Returning the results of side 0: */
  retval = rvt_token_checkInput_retval_output[rv_uf_ind];	/* Generated by:  RVReUfGen::gen_unitrv_input_found_case(615)(620)(386)(290)/ c:\newrvt\rv_temps.cpp:362*/

  } else {

    /* Assert reach-equivalence: side 0 and 1 inputs are equal.*/
    assert( 0 );

  }

  return retval;
}

void rvt_token_initialize_mutual_termination_tokens_checkInput(){
	int rvt_token_i = 0;
		for (rvt_token_i = 0 ; rvt_token_i < rv_UF_K_checkInput ; rvt_token_i++){
			rvt_token_checkInput_call_mark_array0[rvt_token_i] = 0;
			rvt_token_checkInput_call_mark_array1[rvt_token_i] = 0;
		}
		rvt_token_checkInput_count = 0;
		rvt_token_checkInput_first_call_to_uf_flag = 0;

}
