// Global Variables for Unrolling
int rv_unroll_helper_basecase_flag = 0;
// End of Global Variables for Unrolling

/*** global declarations side 0: ***/
int  rvs0_rv_mult_int__int_(int  x, int  y);
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
int  chk0_fact(int  n);
int  rvs0_main();
void  __CPROVER_assume(_Bool  rv_arg_8);

/*** global declarations side 1: ***/
int  rvs1_rv_mult_int__int_(int  x, int  y);
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
int  chk1_fact(int  n);
int  rvs1_main();
void  __CPROVER_assume(_Bool  rv_arg_9);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  rvs0_rv_mult_int__int_(int  x, int  y)
{
  return x * y;
}

float  rvs0_rv_mult(float  x, float  y)
{
  return x * y;
}

int  chk0_fact(int  n)
{
  if (n <= 1)
  {
    return 1;
  }

  return rvs0_rv_mult_int__int_(n,chk0_fact(n - 1));
}

int  rvs0_main()
{
  int  n;

  return chk0_fact(n);
}


/*** Functions side 1: ***/
int  rvs1_rv_mult_int__int_(int  x, int  y)
{
  return x * y;
}

float  rvs1_rv_mult(float  x, float  y)
{
  return x * y;
}

int  chk1_fact_deepest(int  n)
{
  __CPROVER_assume(0);
}

int  chk1_fact(int  n)
{
  if (n <= 0)
  {
    return 1;
  }

  return rvs1_rv_mult_int__int_(n,chk1_fact_deepest(n - 1));
}

int  rvs1_main()
{
  int  n;

  return chk1_fact(n);
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  int  retval0;	/* Generated by:  RVTemp::gen_retval_declarations/ rv_temps.cpp:270*/
  int  retval1;	/* Generated by:  RVTemp::gen_retval_declarations/ rv_temps.cpp:270*/
  int  rvs0_n;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)/ rv_temps.cpp:275*/
  int  rvs1_n;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ rv_temps.cpp:275*/

  /* output: */
  /* Allocations for side 0: */
  /* Allocations for side 1: */

  /* Assume input args are equal: */ 
  rvs0_n = rvs1_n;	/* Generated by:  RVMainGen::gen_args_equality(621)(626)(392)(306)/ rv_temps.cpp:371*/

  /* run each side's main() */

  /* add any pre-computed assumption on the input */
  __CPROVER_assume(1);
  retval1 = chk1_fact(rvs1_n);
  retval0 = chk0_fact(rvs0_n);
  /* Assertions: */

  /* Compare return values: */ 
  assert( retval0 == retval1 );	/* Generated by:  RVMainGen::gen_main(621)(626)(392)(322)/ rv_temps.cpp:361*/

  /* Compare output args: */ 


  return 0;
}
