#include "rv_declarations.h"

/*** global declarations side 0: ***/
int  chk0_main();
unsigned char  rvs0_Loop_main_while1(int  *rvp_x, int  *rvp_rvretval);
unsigned char  rvs0_Loop_main_while1(int  *rvp_x, int  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_4);

/*** global declarations side 1: ***/
int  chk1_main();
unsigned char  rvs1_Loop_main_while1(int  *rvp_x, int  *rvp_rvretval);
unsigned char  rvs1_Loop_main_while1(int  *rvp_x, int  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_5);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  chk0_main()
{
  int  rvretval = 0;
  int  x = 1;
  int  y;

  {
    rvs0_Loop_main_while1(&x,&rvretval);
  }

  return x << 1;
}


/*** Functions side 1: ***/
int  chk1_main()
{
  int  rvretval = 0;
  int  y;
  int  x = 1;

  {
    rvs1_Loop_main_while1(&x,&rvretval);
  }

  return x * 2;
}


/* Implementations of the uninterpreted functions: */

  /* Declarations of the CBMC uninterpreted functions */
int  __CPROVER_uninterpreted_rvp_x(int );
unsigned char  __CPROVER_uninterpreted_retval(int );

  /* CBMC-UF side 0: */ 
unsigned char  rvs0_Loop_main_while1(int  *rvp_x, int  *rvp_rvretval)
{
  unsigned char  retval;

  /* Declarations: */
  int  rv_D4_0;	/* Generated by:  gen_side0_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (rvp_x== 0) {
  rvp_x = &rv_D4_0;	/* Generated by:  gen_side0_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:332*/
  }

  /* Each output is assigned a UF:*/
  *rvp_x= __CPROVER_uninterpreted_rvp_x(*rvp_x);
  retval= __CPROVER_uninterpreted_retval(*rvp_x);

  return retval;
}


  /* CBMC-UF side 1: */ 
unsigned char  rvs1_Loop_main_while1(int  *rvp_x, int  *rvp_rvretval)
{
  unsigned char  retval;

  /* Declarations: */
  int  rv_D5_0;	/* Generated by:  gen_side1_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (rvp_x== 0) {
  rvp_x = &rv_D5_0;	/* Generated by:  gen_side1_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:332*/
  }

  /* Each output is assigned a UF:*/
  *rvp_x= __CPROVER_uninterpreted_rvp_x(*rvp_x);
  retval= __CPROVER_uninterpreted_retval(*rvp_x);

  return retval;
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  int  retval0;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/
  int  retval1;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/


  /* Assume input args are equal: */ 

  /* run each side's main() */
  retval0 = chk0_main();
  retval1 = chk1_main();
  /* Assertions: */

  /* Compare return values: */ 
  assert( retval0 == retval1 );	/* Generated by:  gen_main(608)(613)(379)(309)/ rv_temps.cpp:352*/

  /* Compare output args: */ 


  return 0;
}
