#include "rv_declarations.h"

/*** global declarations side 0: ***/
int  chk0_f(int  a);
int  rvs0_main();
int  rvs0_f(int  a);
void  __CPROVER_assume(_Bool  rv_arg_2);

/*** global declarations side 1: ***/
int  chk1_f(int  x);
int  rvs1_main();
int  rvs1_f(int  x);
void  __CPROVER_assume(_Bool  rv_arg_3);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  rvs0_f(int  a);
int  chk0_f(int  a)
{
  if (a > 1)
  {
    a = (a & 1) ? (3 * a + 1) : (a / 2);
    return rvs0_f(a);
  }

  return a;
}


/*** Functions side 1: ***/
int  rvs1_f(int  x);
int  chk1_f(int  x)
{
  int  n;

  if (x <= 1)
  {
    return x;
  }

  n = x >> 1;
  if (x % 2)
  {
    n = 6 * n + 4;
  }

  return rvs1_f(n);
}


  /* Declarations of the CBMC uninterpreted functions */
int  __CPROVER_uninterpreted_retval(int );

  /* CBMC-UF side 0: */ 
int  rvs0_f(int  a)
{
  int  retval;

  /* Declarations: */


  /* Each output is assigned a UF:*/
  retval= __CPROVER_uninterpreted_retval(a);
__CPROVER_assume( (!(a <= 2147483647 && -(a) <= 2147483648 ) || ( retval <= 2147483647 && -(retval) <= 2147483648)));
  return retval;
}


  /* CBMC-UF side 1: */ 
int  rvs1_f(int  x)
{
  int  retval;

  /* Declarations: */


  /* Each output is assigned a UF:*/
  retval= __CPROVER_uninterpreted_retval(x);
__CPROVER_assume( (!(x <= 2147483647 && -(x) <= 2147483648 ) || ( retval <= 2147483647 && -(retval) <= 2147483648)));
  return retval;
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  int  retval0;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/
  int  retval1;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/
  int  rvs0_a;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  rvs1_x;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/

  /* output: */
  /* Allocations for side 0: */
  /* Allocations for side 1: */

  /* Assume input args are equal: */ 
  rvs0_a = rvs1_x;	/* Generated by:  RVMainGen::gen_args_equality(621)(626)(392)(306)/ c:\newrvt\rv_temps.cpp:362*/

  /* run each side's main() */
  retval0 = chk0_f(rvs0_a);
  retval1 = chk1_f(rvs1_x);
  /* Assertions: */

  /* Compare return values: */ 
  assert( retval0 == retval1 );	/* Generated by:  RVMainGen::gen_main(621)(626)(392)(322)/ c:\newrvt\rv_temps.cpp:352*/

  /* Compare output args: */ 


  return 0;
}
