#include "rv_declarations.h"
#define RV_MAX_INPUTS 2
#include "rv_inputs.c"
/*** global declarations side 0: ***/
int  rvs0_rv_getint();
char  rvs0_rv_getchar();
void  rvs0_swap(char  *a, char  *b);
char  rvs0_gcd(char  a, char  b);
void  rvs0_simplify(char  *numerator_p, char  *denominator_p);
char  chk0_main();
unsigned char  rvs0_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval);
unsigned char  rvs0_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_28);

/*** global declarations side 1: ***/
int  rvs1_rv_getint();
char  rvs1_rv_getchar();
void  rvs1_swap(char  *a, char  *b);
char  rvs1_gcd(char  a, char  b);
void  rvs1_simplify(char  *numerator_p, char  *denominator_p);
char  chk1_main();
unsigned char  rvs1_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval);
unsigned char  rvs1_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_29);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
char  rvs0_gcd(char  a, char  b)
{
  char  rvretval = 0;

  {
    rvs0_Loop_gcd_while1(&a,&b,&rvretval);
  }

  return b;
}

void  rvs0_simplify(char  *numerator_p, char  *denominator_p)
{
  char  tmp = rvs0_gcd(*numerator_p,*denominator_p);

  *numerator_p = *numerator_p / tmp;
  *denominator_p = *denominator_p / tmp;
}

char  chk0_main()
{
  char  a;
  char  b;

  a = rvs0_rv_getchar();
  b = rvs0_rv_getchar();
  rvs0_simplify(&a,&b);
  return 0;
}


/*** Functions side 1: ***/
char  rvs1_gcd(char  a, char  b)
{
  char  rvretval = 0;

  {
    rvs1_Loop_gcd_while1(&a,&b,&rvretval);
  }

  return b - 1;
}

void  rvs1_simplify(char  *numerator_p, char  *denominator_p)
{
  char  tmp = rvs1_gcd(*numerator_p,*denominator_p);

  *numerator_p = *numerator_p / ++tmp;
  *denominator_p = *denominator_p / tmp;
}

char  chk1_main()
{
  char  b;
  char  a;

  a = 0 + rvs1_rv_getchar();
  b = rvs1_rv_getchar();
  rvs1_simplify(&a,&b);
  return 0;
}


/* Implementations of the uninterpreted functions: */

typedef struct rv_UF_Loop_gcd_while1_struct_tag {
  char  *in_rvp_a;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  char  *out_rvp_a;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  char  *in_rvp_b;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  char  *out_rvp_b;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  unsigned char  out_retval;	/* Generated by:  gen_uf_array(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  _Bool reach_equiv_flag;
} rv_UF_Loop_gcd_while1_struct;
#define rv_UF_K_Loop_gcd_while1 1 /* determined by RVT */
rv_UF_Loop_gcd_while1_struct rv_UF_Loop_gcd_while1_array[rv_UF_K_Loop_gcd_while1];
int rv_UF_Loop_gcd_while1_count[2] = {0,0};


 /*** uninterpreted function side 0: ***/ 
  /* Declarations: */


unsigned char  rvs0_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval)
{
  unsigned char  retval;

  /* save values of input arguments: */
  *rv_UF_Loop_gcd_while1_array[rv_UF_Loop_gcd_while1_count[0]].in_rvp_a = *rvp_a;	/* Generated by:  gen_side0_uf(608)/ protect_pointer [op=4](613)(379)(293)/ rv_temps.cpp:362*/
  *rv_UF_Loop_gcd_while1_array[rv_UF_Loop_gcd_while1_count[0]].in_rvp_b = *rvp_b;	/* Generated by:  gen_side0_uf(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)/ rv_temps.cpp:362*/
  /* save values of input globals: */

  /* generate and save values of output arguments and globals: */
  *rv_UF_Loop_gcd_while1_array[rv_UF_Loop_gcd_while1_count[0]].out_rvp_a = *rvp_a = (char )nondet_int();	/* Generated by:  gen_side0_uf(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=2](613)(379)(265)/ rv_temps.cpp:412*/
  *rv_UF_Loop_gcd_while1_array[rv_UF_Loop_gcd_while1_count[0]].out_rvp_b = *rvp_b = (char )nondet_int();	/* Generated by:  gen_side0_uf(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=2](613)(379)(265)(608)/ protect_pointer [op=2](613)(379)(265)/ rv_temps.cpp:412*/
  rv_UF_Loop_gcd_while1_array[rv_UF_Loop_gcd_while1_count[0]].out_retval = retval = (unsigned char )nondet_int();	/* Generated by:  gen_side0_uf(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=2](613)(379)(265)(608)/ protect_pointer [op=2](613)(379)(265)(608)(613)(379)(265)/ rv_temps.cpp:412*/
  rv_UF_Loop_gcd_while1_count[0]++;

  return retval;
}


/*** uninterpreted function side 1: ***/ 
unsigned char  rvs1_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval)
{
  unsigned char  retval;

  _Bool found = 0;
  _Bool equal = 1;
  int found_ind = -1;
  int rv_uf_ind = rv_UF_Loop_gcd_while1_count[0]-1;
  for(; rv_uf_ind >= 0; rv_uf_ind--) {
    equal = (*rv_UF_Loop_gcd_while1_array[rv_uf_ind].in_rvp_a == *rvp_a);	/* Generated by:  gen_side1_uf(608)/ protect_pointer [op=3](613)(379)(273)/ rv_temps.cpp:419*/
    equal = equal && (*rv_UF_Loop_gcd_while1_array[rv_uf_ind].in_rvp_b == *rvp_b);	/* Generated by:  gen_side1_uf(608)/ protect_pointer [op=3](613)(379)(273)(608)/ protect_pointer [op=3](613)(379)(273)/ rv_temps.cpp:419*/
    if( equal ) { 
      found = 1;
      found_ind = rv_uf_ind;
      rv_UF_Loop_gcd_while1_array[rv_uf_ind].reach_equiv_flag = 1;
    }
  }

  if( found ) /* input values were found among the saved values */
  {
   /* Sides 0 and 1 are partially equivalent.
    * Returning the results of side 0: */
  *rvp_a = *rv_UF_Loop_gcd_while1_array[found_ind].out_rvp_a;	/* Generated by:  gen_input_found_case(608)/ protect_pointer [op=5](613)(379)(284)/ rv_temps.cpp:362*/
  *rvp_b = *rv_UF_Loop_gcd_while1_array[found_ind].out_rvp_b;	/* Generated by:  gen_input_found_case(608)/ protect_pointer [op=5](613)(379)(284)(608)/ protect_pointer [op=5](613)(379)(284)/ rv_temps.cpp:362*/
  retval = rv_UF_Loop_gcd_while1_array[found_ind].out_retval;	/* Generated by:  gen_input_found_case(608)/ protect_pointer [op=5](613)(379)(284)(608)/ protect_pointer [op=5](613)(379)(284)(608)(613)(379)(284)/ rv_temps.cpp:362*/

  } else {

    /* Assert reach-equivalence: side 0 and 1 inputs are equal.*/
    assert( 0 );

  }
  rv_UF_Loop_gcd_while1_count[1]++;

  return retval;
}






void rv_init()
{
}


void rv_check()
{
  /* check reach-equivalence of the inputs for each uninterpreted function: */
  int i;

  /* checking reach-equivalence of all the inputs of array rv_UF_Loop_gcd_while1_array : */
  for (i = rv_UF_Loop_gcd_while1_count[0] - 1; i >= 0; --i)
    assert( rv_UF_Loop_gcd_while1_array[i].reach_equiv_flag );
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  char  retval0;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/
  char  retval1;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/



  rv_init();

  /* Assume input args are equal: */ 

  /* run each side's main() */
  retval0 = chk0_main();
  retval1 = chk1_main();

  rv_check();

  return 0;
}

