#include "rv_declarations.h"

/*** global declarations of both sides: ***/

/*** global declarations side 0: ***/
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
int  chk0_f91(int  a);
int  rvs0_main();
int  rvs0_f91(int  a);
void  __CPROVER_assume(_Bool  rv_arg_2);

/*** global declarations side 1: ***/
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
int  chk1_f91(int  x);
int  rvs1_main();
int  rvs1_f91(int  x);
void  __CPROVER_assume(_Bool  rv_arg_3);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  rvs0_f91(int  a);
int  chk0_f91(int  a)
{
  if (a > 100)
  {
    return a - 10;
  }

  return rvs0_f91(rvs0_f91(a + 11));
}


/*** Functions side 1: ***/
int  rvs1_f91(int  x);
int  chk1_f91(int  x)
{
  if (x < 101)
  {
    return rvs1_f91(rvs1_f91(11 + x));
  }

  return x - 10;
}

#define rv_UF_K_f91 5
//Recording arrays for local parameter input
int  rvt_token_f91_a[rv_UF_K_f91];

//Recording arrays for global input

//Output arrays for local input
int  rvt_token_f91_a_output[rv_UF_K_f91];


//Output arrays for global input

//Output array for function output
int  rvt_token_f91_retval_output[rv_UF_K_f91];

int  rvt_token_f91_call_mark_array0[rv_UF_K_f91];
int  rvt_token_f91_call_mark_array1[rv_UF_K_f91];
int  rvt_token_f91_count;
_Bool  rvt_token_f91_first_call_to_uf_flag;

 /*** uninterpreted function side 0: ***/ 
int  rvs0_f91(int  a)
{
  int  retval;

 /* Zeroing both mark arrays and count variable for unitrv mutual termination check */
  /* save values of input arguments: */
	rvt_token_f91_a[rvt_token_f91_count] = a;
  /* save values of input globals: */

  /* generate and save values of output arguments and globals: */

  /* generate and save value for the functino output : */
  rvt_token_f91_retval_output[rvt_token_f91_count] = retval = (int )nondet_long();	/* Generated by:  RVReUfGen::gen_unitrv_side0_uf(615)(620)(386)(267)/ c:\newrvt\rv_temps.cpp:420*/
	rvt_token_f91_call_mark_array0[rvt_token_f91_count] = 1;
	rvt_token_f91_count++;
  return retval;
}


/*** uninterpreted function side 1: ***/ 
int  rvs1_f91(int  x)
{
  int  retval;

  _Bool found = 0;
  _Bool equal = 1;
  int found_ind = -1;
  int rv_uf_ind = rvt_token_f91_count-1;
  for(; rv_uf_ind >= 0; rv_uf_ind--) {
		equal = equal && x == rvt_token_f91_a[rv_uf_ind];
    if( equal ) { 
      found = 1;
      found_ind = rv_uf_ind;
		rvt_token_f91_call_mark_array1[rv_uf_ind] = 1;
    }
		equal = 1;
  }

  if( found ) /* input values were found among the saved values */
  {
   /* Sides 0 and 1 are partially equivalent.
    * Returning the results of side 0: */
  retval = rvt_token_f91_retval_output[rv_uf_ind];	/* Generated by:  RVReUfGen::gen_unitrv_input_found_case(615)(620)(386)(290)/ c:\newrvt\rv_temps.cpp:362*/

  } else {

    /* Assert reach-equivalence: side 0 and 1 inputs are equal.*/
    assert( 0 );

  }

  return retval;
}

void rvt_token_initialize_mutual_termination_tokens_f91(){
	int rvt_token_i = 0;
		for (rvt_token_i = 0 ; rvt_token_i < rv_UF_K_f91 ; rvt_token_i++){
			rvt_token_f91_call_mark_array0[rvt_token_i] = 0;
			rvt_token_f91_call_mark_array1[rvt_token_i] = 0;
		}
		rvt_token_f91_count = 0;
		rvt_token_f91_first_call_to_uf_flag = 0;

}
