// Global Variables for Unrolling
int rv_unroll_helper_basecase_flag = 0;
// End of Global Variables for Unrolling

/*** global declarations side 0: ***/
short  rvs0_rv_mod_short__short_(short  x, short  y);
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
void  rvs0_swap(short  *a, short  *b);
short  chk0_gcd(short  a, short  b);
short  rvs0_main();
unsigned char  rvs0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_14);

/*** global declarations side 1: ***/
short  rvs1_rv_mod_short__short_(short  x, short  y);
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
void  rvs1_swap(short  *a, short  *b);
short  chk1_gcd(short  a, short  b);
short  rvs1_main();
unsigned char  rvs1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_15);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
float  rvs0_rv_mult(float  x, float  y)
{
  return x * y;
}

void  rvs0_swap(short  *a, short  *b)
{
  short  tmp = *a;

  *a = *b;
  *b = tmp;
}

short  chk0_gcd_deepest(short  a, short  b)
{
  __CPROVER_assume(0);
}

short  chk0_gcd(short  a, short  b)
{
  short  rvretval = 0;

  {
    rvs0_Loop_gcd_while1(&a,&b,&rvretval);
  }

  return b;
}

unsigned char  rvs0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  if (!(*rvp_a != 0))
    return 0;
  {
    *rvp_b = rvs0_rv_mod_short__short_(*rvp_b,*rvp_a);
    rvs0_swap(&*rvp_a,&*rvp_b);
  }

  {
    return rvs0_Loop_gcd_while1(rvp_a,rvp_b,rvp_rvretval);
  }

  return 0;
}

short  rvs0_main()
{
  short  a;
  short  b;

  chk0_gcd(a,b);
  return 0;
}


/*** Functions side 1: ***/
float  rvs1_rv_mult(float  x, float  y)
{
  return x * y;
}

void  rvs1_swap(short  *a, short  *b)
{
  short  tmp = *a;

  *a = *b;
  *b = tmp;
}

short  chk1_gcd(short  a, short  b)
{
  short  rvretval = 0;

  {
    rvs1_Loop_gcd_while1(&a,&b,&rvretval);
  }

  a = 5;
  return b;
}

unsigned char  rvs1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  if (!(*rvp_a != 0))
    return 0;
  {
    *rvp_b = rvs1_rv_mod_short__short_(*rvp_b,*rvp_a);
    rvs1_swap(&*rvp_a,&*rvp_b);
    *rvp_a = *rvp_a;
  }

  {
    return rvs1_Loop_gcd_while1(rvp_a,rvp_b,rvp_rvretval);
  }

  return 0;
}

short  rvs1_main()
{
  short  a;
  short  b;

  chk1_gcd(a,b);
  return 0;
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  short  retval0;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:270*/
  short  retval1;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:270*/
  short  rvs0_a;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  rvs1_a;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  rvs0_b;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  rvs1_b;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/

  /* output: */
  /* output: */
  /* Allocations for side 0: */
  /* Allocations for side 1: */

  /* Assume input args are equal: */ 
  rvs0_a = rvs1_a;	/* Generated by:  RVMainGen::gen_args_equality(621)(626)(392)(306)/ c:\newrvt\rv_temps.cpp:371*/
  rvs0_b = rvs1_b;	/* Generated by:  RVMainGen::gen_args_equality(621)(626)(392)(306)(621)(626)(392)(306)/ c:\newrvt\rv_temps.cpp:371*/

  /* run each side's main() */

  /* add any pre-computed assumption on the input */
  __CPROVER_assume(1);
  retval0 = chk0_gcd(rvs0_a, rvs0_b);
  retval1 = chk1_gcd(rvs1_a, rvs1_b);
  /* Assertions: */

  /* Compare return values: */ 
  assert( retval0 == retval1 );	/* Generated by:  RVMainGen::gen_main(621)(626)(392)(322)/ c:\newrvt\rv_temps.cpp:361*/

  /* Compare output args: */ 


  return 0;
}
