// Global Variables for Unrolling
int rv_unroll_helper_basecase_flag = 0;
// End of Global Variables for Unrolling

/*** global declarations side 0: ***/
short  rvs0_rv_mod_short__short_(short  x, short  y);
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
void  rvs0_swap(short  *a, short  *b);
short  rvs0_gcd(short  a, short  b);
short  rvs0_main();
unsigned char  chk0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_4);

/*** global declarations side 1: ***/
short  rvs1_rv_mod_short__short_(short  x, short  y);
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
void  rvs1_swap(short  *a, short  *b);
short  rvs1_gcd(short  a, short  b);
short  rvs1_main();
unsigned char  chk1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_5);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
float  rvs0_rv_mult(float  x, float  y)
{
  return x * y;
}

void  rvs0_swap(short  *a, short  *b)
{
  short  tmp = *a;

  *a = *b;
  *b = tmp;
}

short  rvs0_gcd(short  a, short  b)
{
  short  rvretval = 0;

  {
    chk0_Loop_gcd_while1(&a,&b,&rvretval);
  }

  return b;
}

unsigned char  chk0_Loop_gcd_while1_deepest(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  __CPROVER_assume(0);
}

unsigned char  chk0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  if (!(*rvp_a != 0))
    return 0;
  {
    *rvp_b = rvs0_rv_mod_short__short_(*rvp_b,*rvp_a);
    rvs0_swap(&*rvp_a,&*rvp_b);
  }

  {
    return chk0_Loop_gcd_while1_deepest(rvp_a,rvp_b,rvp_rvretval);
  }

  return 0;
}

short  rvs0_main()
{
  short  a;
  short  b;

  rvs0_gcd(a,b);
  return 0;
}


/*** Functions side 1: ***/
float  rvs1_rv_mult(float  x, float  y)
{
  return x * y;
}

void  rvs1_swap(short  *a, short  *b)
{
  short  tmp = *a;

  *a = *b;
  *b = tmp;
}

short  rvs1_gcd(short  a, short  b)
{
  short  rvretval = 0;

  {
    chk1_Loop_gcd_while1(&a,&b,&rvretval);
  }

  a = 5;
  return b;
}

unsigned char  chk1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  if (!(*rvp_a != 0))
    return 0;
  {
    *rvp_b = rvs1_rv_mod_short__short_(*rvp_b,*rvp_a);
    rvs1_swap(&*rvp_a,&*rvp_b);
    *rvp_a = *rvp_a;
  }

  {
    return chk1_Loop_gcd_while1(rvp_a,rvp_b,rvp_rvretval);
  }

  return 0;
}

short  rvs1_main()
{
  short  a;
  short  b;

  rvs1_gcd(a,b);
  return 0;
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  unsigned char  retval0;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:270*/
  unsigned char  retval1;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:270*/
  short  *rvs0_rvp_a;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  *rvs1_rvp_a;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  *rvs0_rvp_b;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  *rvs1_rvp_b;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  *rvs0_rvp_rvretval;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  *rvs1_rvp_rvretval;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  rv_D0_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D1_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D2_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D3_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D4_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D5_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/

  /* output: */
  /* output: */
  /* output: */
  /* Allocations for side 0: */
  rvs0_rvp_a = &rv_D0_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  rvs0_rvp_b = &rv_D1_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  rvs0_rvp_rvretval = &rv_D2_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  /* Allocations for side 1: */
  rvs1_rvp_a = &rv_D3_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  rvs1_rvp_b = &rv_D4_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  rvs1_rvp_rvretval = &rv_D5_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/

  /* Assume input args are equal: */ 
  *rvs0_rvp_a = *rvs1_rvp_a;	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=4](626)(392)(306)/ c:\newrvt\rv_temps.cpp:371*/
  *rvs0_rvp_b = *rvs1_rvp_b;	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)/ c:\newrvt\rv_temps.cpp:371*/
  *rvs0_rvp_rvretval = *rvs1_rvp_rvretval;	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)/ c:\newrvt\rv_temps.cpp:371*/

  /* run each side's main() */

  /* add any pre-computed assumption on the input */
  __CPROVER_assume(1);
  retval0 = chk0_Loop_gcd_while1(rvs0_rvp_a, rvs0_rvp_b, rvs0_rvp_rvretval);
  retval1 = chk1_Loop_gcd_while1(rvs1_rvp_a, rvs1_rvp_b, rvs1_rvp_rvretval);
  /* Assertions: */

  /* Compare return values: */ 
  assert( retval0 == retval1 );	/* Generated by:  RVMainGen::gen_main(621)(626)(392)(322)/ c:\newrvt\rv_temps.cpp:361*/

  /* Compare output args: */ 
  assert( *rvs0_rvp_a == *rvs1_rvp_a );	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=6](626)(392)(322)/ c:\newrvt\rv_temps.cpp:361*/
  assert( *rvs0_rvp_b == *rvs1_rvp_b );	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=6](626)(392)(322)(621)/ RVGen::protect_pointer [op=6](626)(392)(322)/ c:\newrvt\rv_temps.cpp:361*/


  return 0;
}
