#include "rv_declarations.h"
// Global Variables for Unrolling
int rv_unroll_helper_basecase_flag = 0;
// End of Global Variables for Unrolling

/*** global declarations side 0: ***/
short  rvs0_rv_mod_short__short_(short  x, short  y);
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
void  rvs0_swap(short  *a, short  *b);
short  rvs0_gcd(short  a, short  b);
short  rvs0_main();
void  rvs0_swap(short  *a, short  *b);
unsigned char  chk0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
unsigned char  rvs0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_10);

/*** global declarations side 1: ***/
short  rvs1_rv_mod_short__short_(short  x, short  y);
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
void  rvs1_swap(short  *a, short  *b);
short  rvs1_gcd(short  a, short  b);
short  rvs1_main();
void  rvs1_swap(short  *a, short  *b);
unsigned char  chk1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
unsigned char  rvs1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_11);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
unsigned char  chk0_Loop_gcd_while1_deepest(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  return rvs0_Loop_gcd_while1(rvp_a,rvp_b,rvp_rvretval);
}

unsigned char  rvs0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
unsigned char  chk0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  if (!(*rvp_a != 0))
    return 0;
  {
    *rvp_b = rvs0_rv_mod_short__short_(*rvp_b,*rvp_a);
    rvs0_swap(&*rvp_a,&*rvp_b);
  }

  {
    return chk0_Loop_gcd_while1_deepest(rvp_a,rvp_b,rvp_rvretval);
  }

  return 0;
}


/*** Functions side 1: ***/
unsigned char  chk1_Loop_gcd_while1_deepest(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  return rvs1_Loop_gcd_while1(rvp_a,rvp_b,rvp_rvretval);
}

unsigned char  rvs1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
unsigned char  chk1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  if (!(*rvp_a != 0))
    return 0;
  {
    *rvp_b = rvs1_rv_mod_short__short_(*rvp_b,*rvp_a);
    rvs1_swap(&*rvp_a,&*rvp_b);
    *rvp_a = *rvp_a;
  }

  {
    return chk1_Loop_gcd_while1_deepest(rvp_a,rvp_b,rvp_rvretval);
  }

  return 0;
}


/* Implementations of the uninterpreted functions: */

  /* Declarations of the CBMC uninterpreted functions */
short  __CPROVER_uninterpreted_retval(short , short );

  /* CBMC-UF side 0: */ 
short  rvs0_rv_mod_short__short_(short  x, short  y)
{
  short  retval;

  /* Declarations: */


  /* Each output is assigned a UF:*/
  retval= __CPROVER_uninterpreted_retval(x, y);
__CPROVER_assume(1);
  return retval;
}


  /* CBMC-UF side 1: */ 
short  rvs1_rv_mod_short__short_(short  x, short  y)
{
  short  retval;

  /* Declarations: */


  /* Each output is assigned a UF:*/
  retval= __CPROVER_uninterpreted_retval(x, y);
__CPROVER_assume(1);
  return retval;
}


  /* Declarations of the CBMC uninterpreted functions */
short  __CPROVER_uninterpreted_1_a(short , short );
short  __CPROVER_uninterpreted_1_b(short , short );

  /* CBMC-UF side 0: */ 
void  rvs0_swap(short  *a, short  *b)
{
  /* Declarations: */
  short  rv_D12_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D13_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (a== 0) {
  a = &rv_D12_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  }
  if (b== 0) {
  b = &rv_D13_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  }

  /* Each output is assigned a UF:*/
  *a= __CPROVER_uninterpreted_1_a(*a, *b);
  *b= __CPROVER_uninterpreted_1_b(*a, *b);
__CPROVER_assume(1);
}


  /* CBMC-UF side 1: */ 
void  rvs1_swap(short  *a, short  *b)
{
  /* Declarations: */
  short  rv_D14_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D15_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (a== 0) {
  a = &rv_D14_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  }
  if (b== 0) {
  b = &rv_D15_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  }

  /* Each output is assigned a UF:*/
  *a= __CPROVER_uninterpreted_1_a(*a, *b);
  *b= __CPROVER_uninterpreted_1_b(*a, *b);
__CPROVER_assume(1);
}


  /* Declarations of the CBMC uninterpreted functions */
short  __CPROVER_uninterpreted_2_rvp_a(short , short , short );
short  __CPROVER_uninterpreted_2_rvp_b(short , short , short );
unsigned char  __CPROVER_uninterpreted_2_retval(short , short , short );

  /* CBMC-UF side 0: */ 
unsigned char  rvs0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  unsigned char  retval;

  /* Declarations: */
  short  rv_D16_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D17_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D18_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (rvp_a== 0) {
  rvp_a = &rv_D16_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  }
  if (rvp_b== 0) {
  rvp_b = &rv_D17_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  }
  if (rvp_rvretval== 0) {
  rvp_rvretval = &rv_D18_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  }

	rv_unroll_helper_basecase_flag++;
  /* Each output is assigned a UF:*/
  *rvp_a= __CPROVER_uninterpreted_2_rvp_a(*rvp_a, *rvp_b, *rvp_rvretval);
  *rvp_b= __CPROVER_uninterpreted_2_rvp_b(*rvp_a, *rvp_b, *rvp_rvretval);
  retval= __CPROVER_uninterpreted_2_retval(*rvp_a, *rvp_b, *rvp_rvretval);
__CPROVER_assume(1);
  return retval;
}


  /* CBMC-UF side 1: */ 
unsigned char  rvs1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  unsigned char  retval;

  /* Declarations: */
  short  rv_D19_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D20_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D21_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (rvp_a== 0) {
  rvp_a = &rv_D19_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  }
  if (rvp_b== 0) {
  rvp_b = &rv_D20_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  }
  if (rvp_rvretval== 0) {
  rvp_rvretval = &rv_D21_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  }
	rv_unroll_helper_basecase_flag++;

  /* Each output is assigned a UF:*/
  *rvp_a= __CPROVER_uninterpreted_2_rvp_a(*rvp_a, *rvp_b, *rvp_rvretval);
  *rvp_b= __CPROVER_uninterpreted_2_rvp_b(*rvp_a, *rvp_b, *rvp_rvretval);
  retval= __CPROVER_uninterpreted_2_retval(*rvp_a, *rvp_b, *rvp_rvretval);
__CPROVER_assume(1);
  return retval;
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  unsigned char  retval0;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:270*/
  unsigned char  retval1;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:270*/
  short  *rvs0_rvp_a;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  *rvs1_rvp_a;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  *rvs0_rvp_b;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  *rvs1_rvp_b;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  *rvs0_rvp_rvretval;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  *rvs1_rvp_rvretval;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:275*/
  short  rv_D22_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D23_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D24_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D25_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D26_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/
  short  rv_D27_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:328*/

  /* output: */
  /* output: */
  /* output: */
  /* Allocations for side 0: */
  rvs0_rvp_a = &rv_D22_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  rvs0_rvp_b = &rv_D23_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  rvs0_rvp_rvretval = &rv_D24_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  /* Allocations for side 1: */
  rvs1_rvp_a = &rv_D25_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  rvs1_rvp_b = &rv_D26_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/
  rvs1_rvp_rvretval = &rv_D27_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:333*/

  /* Assume input args are equal: */ 
  *rvs0_rvp_a = *rvs1_rvp_a;	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=4](626)(392)(306)/ c:\newrvt\rv_temps.cpp:371*/
  *rvs0_rvp_b = *rvs1_rvp_b;	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)/ c:\newrvt\rv_temps.cpp:371*/
  *rvs0_rvp_rvretval = *rvs1_rvp_rvretval;	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)/ c:\newrvt\rv_temps.cpp:371*/

  /* run each side's main() */

  /* add any pre-computed assumption on the input */
  __CPROVER_assume(1);
  retval0 = chk0_Loop_gcd_while1(rvs0_rvp_a, rvs0_rvp_b, rvs0_rvp_rvretval);
  retval1 = chk1_Loop_gcd_while1(rvs1_rvp_a, rvs1_rvp_b, rvs1_rvp_rvretval);
  /* Assertions: */

  /* Compare return values: */ 
  assert( ( rv_unroll_helper_basecase_flag < 2) || retval0 == retval1 );	/* Generated by:  RVMainGen::gen_main(621)(626)(392)(322)/ c:\newrvt\rv_temps.cpp:361*/

  /* Compare output args: */ 
  assert( ( rv_unroll_helper_basecase_flag < 2) || *rvs0_rvp_a == *rvs1_rvp_a );	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=6](626)(392)(322)/ c:\newrvt\rv_temps.cpp:361*/
  assert( ( rv_unroll_helper_basecase_flag < 2) || *rvs0_rvp_b == *rvs1_rvp_b );	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=6](626)(392)(322)(621)/ RVGen::protect_pointer [op=6](626)(392)(322)/ c:\newrvt\rv_temps.cpp:361*/


  return 0;
}
