#include "rv_declarations.h"

/*** global declarations side 0: ***/
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
void  __CPROVER_assume(_Bool  rv_arg_0);
void  assert(_Bool  rv_arg_1);
void  rvs0_bubble_sort(int  *a, int  sz);
int  rvs0_a[5];
void  rvs0_bubble_sort(int  *a, int  sz);
int  rvs0_init_array(int  n);
int  rvs0_main();
unsigned char  rvs0_Loop_bubble_sort_for1(int  *a, int  sz, int  *rvp_i);
unsigned char  chk0_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
unsigned char  rvs0_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
void  __CPROVER_assume(_Bool  rv_arg_6);

/*** global declarations side 1: ***/
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
void  __CPROVER_assume(_Bool  rv_arg_2);
void  assert(_Bool  rv_arg_3);
void  rvs1_bubble_sort(int  *a, int  sz);
int  rvs1_a[5];
void  rvs1_bubble_sort(int  *a, int  sz);
int  rvs1_init_array(int  n);
int  rvs1_main();
unsigned char  rvs1_Loop_bubble_sort_for1(int  *a, int  sz, int  *rvp_i);
unsigned char  chk1_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
unsigned char  rvs1_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
void  __CPROVER_assume(_Bool  rv_arg_7);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
unsigned char  rvs0_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
unsigned char  chk0_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j)
{
  int  t;

  if (!(*rvp_j < i))
    return 0;
  {
    __CPROVER_assume(*rvp_j < 4 && *rvp_j >= 0);
    if (a[*rvp_j] < a[*rvp_j + 1])
    {
      t = a[*rvp_j];
      a[*rvp_j] = a[*rvp_j + 1];
      a[*rvp_j + 1] = t;
      a[*rvp_j] = a[*rvp_j];
    }

  }

  (*rvp_j)++;
  {
    return rvs0_Loop_bubble_sort_for1_for1(a,i,rvp_j);
  }

  return 0;
}


/*** Functions side 1: ***/
unsigned char  rvs1_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
unsigned char  chk1_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j)
{
  int  t;

  if (!(*rvp_j < i))
    return 0;
  {
    __CPROVER_assume(*rvp_j < 4 && *rvp_j >= 0);
    if (*(a + *rvp_j) < *(a + *rvp_j + 1))
    {
      t = *(a + *rvp_j);
      *(a + *rvp_j) = *(a + *rvp_j + 1);
      *(a + *rvp_j + 1) = t;
    }

    *rvp_j = *rvp_j + 1;
  }

  {
    return rvs1_Loop_bubble_sort_for1_for1(a,i,rvp_j);
  }

  return 0;
}


typedef struct rv_UF_Loop_bubble_sort_for1_for1_struct_tag {
  int  in_a[5];	/* Generated by:  RVUFGen::gen_uf_item_decl(114)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  out_a[5];	/* Generated by:  RVUFGen::gen_uf_item_decl(114)/ RVGen::gen_decl_low(151)(114)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  in_i;	/* Generated by:  RVUFGen::gen_uf_item_decl(114)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  *in_rvp_j;	/* Generated by:  RVUFGen::gen_uf_item_decl(114)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  *out_rvp_j;	/* Generated by:  RVUFGen::gen_uf_item_decl(114)/ RVGen::gen_decl_low(151)(114)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  unsigned char  out_retval;	/* Generated by:  RVUFGen::gen_uf_array(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  _Bool reach_equiv_flag;
} rv_UF_Loop_bubble_sort_for1_for1_struct;
#define rv_UF_K_Loop_bubble_sort_for1_for1 5
rv_UF_Loop_bubble_sort_for1_for1_struct rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_K_Loop_bubble_sort_for1_for1];
int rv_UF_Loop_bubble_sort_for1_for1_count[2] = {0,0};


 /*** uninterpreted function side 0: ***/ 
  /* Declarations: */


unsigned char  rvs0_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j)
{
  unsigned char  retval;

  /* save values of input arguments: */
  RVT_COPY_ARRAY(rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].,a, 5);	/* Generated by:  RVUFGen::gen_side0_uf(621)(626)(392)(302)/ c:\newrvt\rv_temps.cpp:368*/
  rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].in_i = i;	/* Generated by:  RVUFGen::gen_side0_uf(621)(626)(392)(302)(621)(626)(392)(306)/ c:\newrvt\rv_temps.cpp:362*/
  *rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].in_rvp_j = *rvp_j;	/* Generated by:  RVUFGen::gen_side0_uf(621)(626)(392)(302)(621)(626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)/ c:\newrvt\rv_temps.cpp:362*/
  /* save values of input globals: */

  /* generate and save values of output arguments and globals: */
  RVT_NONDET_ARRAY(rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].,5);	/* Generated by:  RVUFGen::gen_side0_uf(621)(626)(392)(302)(621)(626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)(626)(392)(270)/ c:\newrvt\rv_temps.cpp:388*/
  RVT_COPY_ARRAY(a,rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]]., 5);	/* Generated by:  RVUFGen::gen_side0_uf(621)(626)(392)(302)(621)(626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)(626)(392)(270)/ c:\newrvt\rv_temps.cpp:389*/
  *rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].out_rvp_j = *rvp_j = (int )nondet_long();	/* Generated by:  RVUFGen::gen_side0_uf(621)(626)(392)(302)(621)(626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)(626)(392)(270)(621)/ RVGen::protect_pointer [op=2](626)(392)(276)/ c:\newrvt\rv_temps.cpp:412*/
  rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]]. = retval = (unsigned char )nondet_int();	/* Generated by:  RVUFGen::gen_side0_uf(621)(626)(392)(302)(621)(626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)(626)(392)(270)(621)/ RVGen::protect_pointer [op=2](626)(392)(276)(621)(626)(392)(276)/ c:\newrvt\rv_temps.cpp:412*/
  rv_UF_Loop_bubble_sort_for1_for1_count[0]++;

  return retval;
}


/*** uninterpreted function side 1: ***/ 
unsigned char  rvs1_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j)
{
  unsigned char  retval;

  _Bool found = 0;
  _Bool equal = 1;
  int found_ind = -1;
  int rv_uf_ind = rv_UF_Loop_bubble_sort_for1_for1_count[0]-1;
  for(; rv_uf_ind >= 0; rv_uf_ind--) {
  RVT_COMP_ARRAY(equal,rv_UF_Loop_bubble_sort_for1_for1_array[rv_uf_ind].,a,5);	/* Generated by:  RVUFGen::gen_side1_uf(621)(626)(392)(284)/ c:\newrvt\rv_temps.cpp:394*/
    equal = equal && (rv_UF_Loop_bubble_sort_for1_for1_array[rv_uf_ind].in_i == i);	/* Generated by:  RVUFGen::gen_side1_uf(621)(626)(392)(284)(621)(626)(392)(285)/ c:\newrvt\rv_temps.cpp:427*/
    equal = equal && (*rv_UF_Loop_bubble_sort_for1_for1_array[rv_uf_ind].in_rvp_j == *rvp_j);	/* Generated by:  RVUFGen::gen_side1_uf(621)(626)(392)(284)(621)(626)(392)(285)(621)/ RVGen::protect_pointer [op=3](626)(392)(285)/ c:\newrvt\rv_temps.cpp:427*/
    if( equal ) { 
      found = 1;
      found_ind = rv_uf_ind;
		      rv_UF_Loop_bubble_sort_for1_for1_array[rv_uf_ind].reach_equiv_flag = 1;
    }
		equal = 1;
  }

  if( found ) /* input values were found among the saved values */
  {
   /* Sides 0 and 1 are partially equivalent.
    * Returning the results of side 0: */
  RVT_COPY_ARRAY(a,rv_UF_Loop_bubble_sort_for1_for1_array[found_ind]., 5);	/* Generated by:  RVUFGen::gen_input_found_case(621)(626)(392)(291)/ c:\newrvt\rv_temps.cpp:368*/
  *rvp_j = *rv_UF_Loop_bubble_sort_for1_for1_array[found_ind].out_rvp_j;	/* Generated by:  RVUFGen::gen_input_found_case(621)(626)(392)(291)(621)/ RVGen::protect_pointer [op=5](626)(392)(296)/ c:\newrvt\rv_temps.cpp:362*/
  retval = rv_UF_Loop_bubble_sort_for1_for1_array[found_ind].;	/* Generated by:  RVUFGen::gen_input_found_case(621)(626)(392)(291)(621)/ RVGen::protect_pointer [op=5](626)(392)(296)(621)(626)(392)(296)/ c:\newrvt\rv_temps.cpp:362*/

  } else {

    /* Assert reach-equivalence: side 0 and 1 inputs are equal.*/
    assert( 0 );

  }
  rv_UF_Loop_bubble_sort_for1_for1_count[1]++;

  return retval;
}

void rvt_token_initialize_mutual_termination_tokens_Loop_bubble_sort_for1_for1(){
	int rvt_token_i = 0;
		for (rvt_token_i = 0 ; rvt_token_i < rv_UF_K_Loop_bubble_sort_for1_for1 ; rvt_token_i++){
			rvt_token_Loop_bubble_sort_for1_for1_call_mark_array0[rvt_token_i] = 0;
			rvt_token_Loop_bubble_sort_for1_for1_call_mark_array1[rvt_token_i] = 0;
		}
		rvt_token_Loop_bubble_sort_for1_for1_count = 0;
		rvt_token_Loop_bubble_sort_for1_for1_first_call_to_uf_flag = 0;

}





void rv_init()
{
}


void rv_check()
{
  /* check reach-equivalence of the inputs for each uninterpreted function: */
  int i;

  /* checking reach-equivalence of all the inputs of array rv_UF_Loop_bubble_sort_for1_for1_array : */
  for (i = rv_UF_Loop_bubble_sort_for1_for1_count[0] - 1; i >= 0; --i)
    assert( rv_UF_Loop_bubble_sort_for1_for1_array[i].reach_equiv_flag );
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  unsigned char  retval0;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/
  unsigned char  retval1;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/
  int  rvs0_a[5];	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  rvs1_a[5];	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  rvs0_i;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  rvs1_i;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  *rvs0_rvp_j;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  *rvs1_rvp_j;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  rv_D0_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(614)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  int  rv_D1_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(614)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/


  /* output: */
  /* output: */
  /* output: */
  /* Allocations for side 0: */
  rvs0_rvp_j = &rv_D0_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(614)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  /* Allocations for side 1: */
  rvs1_rvp_j = &rv_D1_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(614)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/

  rv_init();

  /* Assume input args are equal: */ 
  RVT_COPY_ARRAY(rvs0_a,rvs1_a, 5);	/* Generated by:  RVMainGen::gen_args_equality(621)(626)(392)(302)/ c:\newrvt\rv_temps.cpp:368*/
  rvs0_i = rvs1_i;	/* Generated by:  RVMainGen::gen_args_equality(621)(626)(392)(302)(621)(626)(392)(306)/ c:\newrvt\rv_temps.cpp:362*/
  *rvs0_rvp_j = *rvs1_rvp_j;	/* Generated by:  RVMainGen::gen_args_equality(621)(626)(392)(302)(621)(626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)/ c:\newrvt\rv_temps.cpp:362*/

  /* run each side's main() */
  retval0 = chk0_Loop_bubble_sort_for1_for1(rvs0_a, rvs0_i, rvs0_rvp_j);
  retval1 = chk1_Loop_bubble_sort_for1_for1(rvs1_a, rvs1_i, rvs1_rvp_j);

  rv_check();

  return 0;
}
