#include "rv_declarations.h"

/*** global declarations side 0: ***/
int  rvs0_checkInput(int  n);
int  chk0_f(int  n);
int  rvs0_main();
int  rvs0_checkInput(int  n);
unsigned char  rvs0_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
unsigned char  rvs0_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_2);

/*** global declarations side 1: ***/
int  rvs1_checkInput(int  n);
int  chk1_f(int  n);
int  rvs1_main();
int  rvs1_checkInput(int  n);
unsigned char  rvs1_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
unsigned char  rvs1_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_3);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  chk0_f(int  n)
{
  int  rvretval = 0;

  if (rvs0_checkInput(n))
    return 0;
  int  i;
  int  sum = 0;
  {
    i = 1;
    rvs0_Loop_f_for1(n,&i,&sum,&rvretval);
  }

  return sum;
}


/*** Functions side 1: ***/
int  chk1_f(int  n)
{
  int  rvretval = 0;

  if (rvs1_checkInput(n))
    return 0;
  int  sum = 0;
  {
    int  i = 1;

    {
      rvs1_Loop_f_for1(n,&i,&sum,&rvretval);
    }

  }

  return sum;
}


/* Implementations of the uninterpreted functions: */

typedef struct rv_UF_Loop_f_for1_struct_tag {
  int  in_n;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  *in_rvp_i;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  *out_rvp_i;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  *in_rvp_sum;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  *out_rvp_sum;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  unsigned char  out_retval;	/* Generated by:  gen_uf_array(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  _Bool reach_equiv_flag;
} rv_UF_Loop_f_for1_struct;
#define rv_UF_K_Loop_f_for1 1 /* determined by RVT */
rv_UF_Loop_f_for1_struct rv_UF_Loop_f_for1_array[rv_UF_K_Loop_f_for1];
int rv_UF_Loop_f_for1_count[2] = {0,0};


 /*** uninterpreted function side 0: ***/ 
  /* Declarations: */


unsigned char  rvs0_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval)
{
  unsigned char  retval;

  /* save values of input arguments: */
  rv_UF_Loop_f_for1_array[rv_UF_Loop_f_for1_count[0]].in_n = n;	/* Generated by:  gen_side0_uf(608)(613)(379)(293)/ rv_temps.cpp:362*/
  *rv_UF_Loop_f_for1_array[rv_UF_Loop_f_for1_count[0]].in_rvp_i = *rvp_i;	/* Generated by:  gen_side0_uf(608)(613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)/ rv_temps.cpp:362*/
  *rv_UF_Loop_f_for1_array[rv_UF_Loop_f_for1_count[0]].in_rvp_sum = *rvp_sum;	/* Generated by:  gen_side0_uf(608)(613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)/ rv_temps.cpp:362*/
  /* save values of input globals: */

  /* generate and save values of output arguments and globals: */
  *rv_UF_Loop_f_for1_array[rv_UF_Loop_f_for1_count[0]].out_rvp_i = *rvp_i = (int )nondet_long();	/* Generated by:  gen_side0_uf(608)(613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=2](613)(379)(265)/ rv_temps.cpp:412*/
  *rv_UF_Loop_f_for1_array[rv_UF_Loop_f_for1_count[0]].out_rvp_sum = *rvp_sum = (int )nondet_long();	/* Generated by:  gen_side0_uf(608)(613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=2](613)(379)(265)(608)/ protect_pointer [op=2](613)(379)(265)/ rv_temps.cpp:412*/
  rv_UF_Loop_f_for1_array[rv_UF_Loop_f_for1_count[0]].out_retval = retval = (unsigned char )nondet_int();	/* Generated by:  gen_side0_uf(608)(613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)/ protect_pointer [op=2](613)(379)(265)(608)/ protect_pointer [op=2](613)(379)(265)(608)(613)(379)(265)/ rv_temps.cpp:412*/
  rv_UF_Loop_f_for1_count[0]++;

  return retval;
}


/*** uninterpreted function side 1: ***/ 
unsigned char  rvs1_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval)
{
  unsigned char  retval;

  _Bool found = 0;
  _Bool equal = 1;
  int found_ind = -1;
  int rv_uf_ind = rv_UF_Loop_f_for1_count[0]-1;
  for(; rv_uf_ind >= 0; rv_uf_ind--) {
    equal = (rv_UF_Loop_f_for1_array[rv_uf_ind].in_n == n);	/* Generated by:  gen_side1_uf(608)(613)(379)(273)/ rv_temps.cpp:419*/
    equal = equal && (*rv_UF_Loop_f_for1_array[rv_uf_ind].in_rvp_i == *rvp_i);	/* Generated by:  gen_side1_uf(608)(613)(379)(273)(608)/ protect_pointer [op=3](613)(379)(273)/ rv_temps.cpp:419*/
    equal = equal && (*rv_UF_Loop_f_for1_array[rv_uf_ind].in_rvp_sum == *rvp_sum);	/* Generated by:  gen_side1_uf(608)(613)(379)(273)(608)/ protect_pointer [op=3](613)(379)(273)(608)/ protect_pointer [op=3](613)(379)(273)/ rv_temps.cpp:419*/
    if( equal ) { 
      found = 1;
      found_ind = rv_uf_ind;
      rv_UF_Loop_f_for1_array[rv_uf_ind].reach_equiv_flag = 1;
    }
  }

  if( found ) /* input values were found among the saved values */
  {
   /* Sides 0 and 1 are partially equivalent.
    * Returning the results of side 0: */
  *rvp_i = *rv_UF_Loop_f_for1_array[found_ind].out_rvp_i;	/* Generated by:  gen_input_found_case(608)/ protect_pointer [op=5](613)(379)(284)/ rv_temps.cpp:362*/
  *rvp_sum = *rv_UF_Loop_f_for1_array[found_ind].out_rvp_sum;	/* Generated by:  gen_input_found_case(608)/ protect_pointer [op=5](613)(379)(284)(608)/ protect_pointer [op=5](613)(379)(284)/ rv_temps.cpp:362*/
  retval = rv_UF_Loop_f_for1_array[found_ind].out_retval;	/* Generated by:  gen_input_found_case(608)/ protect_pointer [op=5](613)(379)(284)(608)/ protect_pointer [op=5](613)(379)(284)(608)(613)(379)(284)/ rv_temps.cpp:362*/

  } else {

    /* Assert reach-equivalence: side 0 and 1 inputs are equal.*/
    assert( 0 );

  }
  rv_UF_Loop_f_for1_count[1]++;

  return retval;
}


typedef struct rv_UF_checkInput_struct_tag {
  int  in_n;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  out_retval;	/* Generated by:  gen_uf_array(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  _Bool reach_equiv_flag;
} rv_UF_checkInput_struct;
#define rv_UF_K_checkInput 1 /* determined by RVT */
rv_UF_checkInput_struct rv_UF_checkInput_array[rv_UF_K_checkInput];
int rv_UF_checkInput_count[2] = {0,0};


 /*** uninterpreted function side 0: ***/ 
  /* Declarations: */


int  rvs0_checkInput(int  n)
{
  int  retval;

  /* save values of input arguments: */
  rv_UF_checkInput_array[rv_UF_checkInput_count[0]].in_n = n;	/* Generated by:  gen_side0_uf(608)(613)(379)(293)/ rv_temps.cpp:362*/
  /* save values of input globals: */

  /* generate and save values of output arguments and globals: */
  rv_UF_checkInput_array[rv_UF_checkInput_count[0]].out_retval = retval = (int )nondet_long();	/* Generated by:  gen_side0_uf(608)(613)(379)(293)(608)(613)(379)(265)/ rv_temps.cpp:412*/
  rv_UF_checkInput_count[0]++;

  return retval;
}


/*** uninterpreted function side 1: ***/ 
int  rvs1_checkInput(int  n)
{
  int  retval;

  _Bool found = 0;
  _Bool equal = 1;
  int found_ind = -1;
  int rv_uf_ind = rv_UF_checkInput_count[0]-1;
  for(; rv_uf_ind >= 0; rv_uf_ind--) {
    equal = (rv_UF_checkInput_array[rv_uf_ind].in_n == n);	/* Generated by:  gen_side1_uf(608)(613)(379)(273)/ rv_temps.cpp:419*/
    if( equal ) { 
      found = 1;
      found_ind = rv_uf_ind;
      rv_UF_checkInput_array[rv_uf_ind].reach_equiv_flag = 1;
    }
  }

  if( found ) /* input values were found among the saved values */
  {
   /* Sides 0 and 1 are partially equivalent.
    * Returning the results of side 0: */
  retval = rv_UF_checkInput_array[found_ind].out_retval;	/* Generated by:  gen_input_found_case(608)(613)(379)(284)/ rv_temps.cpp:362*/

  } else {

    /* Assert reach-equivalence: side 0 and 1 inputs are equal.*/
    assert( 0 );

  }
  rv_UF_checkInput_count[1]++;

  return retval;
}






void rv_init()
{
}


void rv_check()
{
  /* check reach-equivalence of the inputs for each uninterpreted function: */
  int i;

  /* checking reach-equivalence of all the inputs of array rv_UF_Loop_f_for1_array : */
  for (i = rv_UF_Loop_f_for1_count[0] - 1; i >= 0; --i)
    assert( rv_UF_Loop_f_for1_array[i].reach_equiv_flag );

  /* checking reach-equivalence of all the inputs of array rv_UF_checkInput_array : */
  for (i = rv_UF_checkInput_count[0] - 1; i >= 0; --i)
    assert( rv_UF_checkInput_array[i].reach_equiv_flag );
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  int  retval0;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/
  int  retval1;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/
  int  rvs0_n;	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  rvs1_n;	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/


  /* output: */
  /* Allocations for side 0: */
  /* Allocations for side 1: */

  rv_init();

  /* Assume input args are equal: */ 
  rvs0_n = rvs1_n;	/* Generated by:  gen_args_equality(608)(613)(379)(293)/ rv_temps.cpp:362*/

  /* run each side's main() */
  retval0 = chk0_f(rvs0_n);
  retval1 = chk1_f(rvs1_n);

  rv_check();

  return 0;
}

