#include "rv_declarations.h"

/*** global declarations side 0: ***/
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
void  __CPROVER_assume(_Bool  rv_arg_0);
void  assert(_Bool  rv_arg_1);
void  rvs0_bubble_sort(int  *a, int  sz);
int  rvs0_a[5];
void  rvs0_bubble_sort(int  *a, int  sz);
int  rvs0_init_array(int  n);
int  rvs0_main();
unsigned char  chk0_Loop_bubble_sort_for1(int  *a, int  sz, int  *rvp_i);
unsigned char  rvs0_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
unsigned char  rvs0_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
void  __CPROVER_assume(_Bool  rv_arg_8);

/*** global declarations side 1: ***/
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
void  __CPROVER_assume(_Bool  rv_arg_2);
void  assert(_Bool  rv_arg_3);
void  rvs1_bubble_sort(int  *a, int  sz);
int  rvs1_a[5];
void  rvs1_bubble_sort(int  *a, int  sz);
int  rvs1_init_array(int  n);
int  rvs1_main();
unsigned char  chk1_Loop_bubble_sort_for1(int  *a, int  sz, int  *rvp_i);
unsigned char  rvs1_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
unsigned char  rvs1_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
void  __CPROVER_assume(_Bool  rv_arg_9);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
unsigned char  chk0_Loop_bubble_sort_for1(int  *a, int  sz, int  *rvp_i)
{
  int  j;
  int  t;

  if (!(*rvp_i > 0))
    return 0;
  {
    {
      unsigned char  rv_ltc_val;

      j = 0;
      rv_ltc_val = rvs0_Loop_bubble_sort_for1_for1(a,*rvp_i,&j);
    }

  }

  (*rvp_i)--;
  return 0;
}


/*** Functions side 1: ***/
unsigned char  chk1_Loop_bubble_sort_for1(int  *a, int  sz, int  *rvp_i)
{
  int  j;
  int  t;

  if (!(*rvp_i > 0))
    return 0;
  {
    {
      unsigned char  rv_ltc_val;

      j = 0;
      rv_ltc_val = rvs1_Loop_bubble_sort_for1_for1(a,*rvp_i,&j);
    }

    *rvp_i = *rvp_i - 1;
  }

  return 0;
}


/* Implementations of the uninterpreted functions: */

typedef struct rv_UF_Loop_bubble_sort_for1_for1_struct_tag {
  int  in_a[5];	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  out_a[5];	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  in_i;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  *in_rvp_j;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  *out_rvp_j;	/* Generated by:  gen_uf_item_decl(111)/ gen_decl_low(148)(111)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  unsigned char  out_retval;	/* Generated by:  gen_uf_array(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  _Bool reach_equiv_flag;
} rv_UF_Loop_bubble_sort_for1_for1_struct;
#define rv_UF_K_Loop_bubble_sort_for1_for1 1 /* determined by RVT */
rv_UF_Loop_bubble_sort_for1_for1_struct rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_K_Loop_bubble_sort_for1_for1];
int rv_UF_Loop_bubble_sort_for1_for1_count[2] = {0,0};


 /*** uninterpreted function side 0: ***/ 
  /* Declarations: */


unsigned char  rvs0_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j)
{
  unsigned char  retval;

  /* save values of input arguments: */
  RVT_COPY_ARRAY(rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].in_a,a, 5);	/* Generated by:  gen_side0_uf(608)(613)(379)(289)/ rv_temps.cpp:368*/
  rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].in_i = i;	/* Generated by:  gen_side0_uf(608)(613)(379)(289)(608)(613)(379)(293)/ rv_temps.cpp:362*/
  *rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].in_rvp_j = *rvp_j;	/* Generated by:  gen_side0_uf(608)(613)(379)(289)(608)(613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)/ rv_temps.cpp:362*/
  /* save values of input globals: */

  /* generate and save values of output arguments and globals: */
  RVT_NONDET_ARRAY(rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].out_a,5);	/* Generated by:  gen_side0_uf(608)(613)(379)(289)(608)(613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)(613)(379)(263)/ rv_temps.cpp:388*/
  RVT_COPY_ARRAY(a,rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].out_a, 5);	/* Generated by:  gen_side0_uf(608)(613)(379)(289)(608)(613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)(613)(379)(263)/ rv_temps.cpp:389*/
  *rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].out_rvp_j = *rvp_j = (int )nondet_long();	/* Generated by:  gen_side0_uf(608)(613)(379)(289)(608)(613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)(613)(379)(263)(608)/ protect_pointer [op=2](613)(379)(265)/ rv_temps.cpp:412*/
  rv_UF_Loop_bubble_sort_for1_for1_array[rv_UF_Loop_bubble_sort_for1_for1_count[0]].out_retval = retval = (unsigned char )nondet_int();	/* Generated by:  gen_side0_uf(608)(613)(379)(289)(608)(613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)(608)(613)(379)(263)(608)/ protect_pointer [op=2](613)(379)(265)(608)(613)(379)(265)/ rv_temps.cpp:412*/
  rv_UF_Loop_bubble_sort_for1_for1_count[0]++;

  return retval;
}


/*** uninterpreted function side 1: ***/ 
unsigned char  rvs1_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j)
{
  unsigned char  retval;

  _Bool found = 0;
  _Bool equal = 1;
  int found_ind = -1;
  int rv_uf_ind = rv_UF_Loop_bubble_sort_for1_for1_count[0]-1;
  for(; rv_uf_ind >= 0; rv_uf_ind--) {
  RVT_COMP_ARRAY(equal,rv_UF_Loop_bubble_sort_for1_for1_array[rv_uf_ind].in_a,a,5);	/* Generated by:  gen_side1_uf(608)(613)(379)(272)/ rv_temps.cpp:394*/
    equal = equal && (rv_UF_Loop_bubble_sort_for1_for1_array[rv_uf_ind].in_i == i);	/* Generated by:  gen_side1_uf(608)(613)(379)(272)(608)(613)(379)(273)/ rv_temps.cpp:419*/
    equal = equal && (*rv_UF_Loop_bubble_sort_for1_for1_array[rv_uf_ind].in_rvp_j == *rvp_j);	/* Generated by:  gen_side1_uf(608)(613)(379)(272)(608)(613)(379)(273)(608)/ protect_pointer [op=3](613)(379)(273)/ rv_temps.cpp:419*/
    if( equal ) { 
      found = 1;
      found_ind = rv_uf_ind;
      rv_UF_Loop_bubble_sort_for1_for1_array[rv_uf_ind].reach_equiv_flag = 1;
    }
  }

  if( found ) /* input values were found among the saved values */
  {
   /* Sides 0 and 1 are partially equivalent.
    * Returning the results of side 0: */
  RVT_COPY_ARRAY(a,rv_UF_Loop_bubble_sort_for1_for1_array[found_ind].out_a, 5);	/* Generated by:  gen_input_found_case(608)(613)(379)(279)/ rv_temps.cpp:368*/
  *rvp_j = *rv_UF_Loop_bubble_sort_for1_for1_array[found_ind].out_rvp_j;	/* Generated by:  gen_input_found_case(608)(613)(379)(279)(608)/ protect_pointer [op=5](613)(379)(284)/ rv_temps.cpp:362*/
  retval = rv_UF_Loop_bubble_sort_for1_for1_array[found_ind].out_retval;	/* Generated by:  gen_input_found_case(608)(613)(379)(279)(608)/ protect_pointer [op=5](613)(379)(284)(608)(613)(379)(284)/ rv_temps.cpp:362*/

  } else {

    /* Assert reach-equivalence: side 0 and 1 inputs are equal.*/
    assert( 0 );

  }
  rv_UF_Loop_bubble_sort_for1_for1_count[1]++;

  return retval;
}






void rv_init()
{
}


void rv_check()
{
  /* check reach-equivalence of the inputs for each uninterpreted function: */
  int i;

  /* checking reach-equivalence of all the inputs of array rv_UF_Loop_bubble_sort_for1_for1_array : */
  for (i = rv_UF_Loop_bubble_sort_for1_for1_count[0] - 1; i >= 0; --i)
    assert( rv_UF_Loop_bubble_sort_for1_for1_array[i].reach_equiv_flag );
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  unsigned char  retval0;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/
  unsigned char  retval1;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/
  int  rvs0_a[5];	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  rvs1_a[5];	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  rvs0_sz;	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  rvs1_sz;	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  *rvs0_rvp_i;	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  *rvs1_rvp_i;	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  rv_D2_0;	/* Generated by:  gen_arg_alloc_side(601)(601)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:327*/
  int  rv_D3_0;	/* Generated by:  gen_arg_alloc_side(601)(601)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:327*/


  /* output: */
  /* output: */
  /* output: */
  /* Allocations for side 0: */
  rvs0_rvp_i = &rv_D2_0;	/* Generated by:  gen_arg_alloc_side(601)(601)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:332*/
  /* Allocations for side 1: */
  rvs1_rvp_i = &rv_D3_0;	/* Generated by:  gen_arg_alloc_side(601)(601)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:332*/

  rv_init();

  /* Assume input args are equal: */ 
  RVT_COPY_ARRAY(rvs0_a,rvs1_a, 5);	/* Generated by:  gen_args_equality(608)(613)(379)(289)/ rv_temps.cpp:368*/
  rvs0_sz = rvs1_sz;	/* Generated by:  gen_args_equality(608)(613)(379)(289)(608)(613)(379)(293)/ rv_temps.cpp:362*/
  *rvs0_rvp_i = *rvs1_rvp_i;	/* Generated by:  gen_args_equality(608)(613)(379)(289)(608)(613)(379)(293)(608)/ protect_pointer [op=4](613)(379)(293)/ rv_temps.cpp:362*/

  /* run each side's main() */
  retval0 = chk0_Loop_bubble_sort_for1(rvs0_a, rvs0_sz, rvs0_rvp_i);
  retval1 = chk1_Loop_bubble_sort_for1(rvs1_a, rvs1_sz, rvs1_rvp_i);

  rv_check();

  return 0;
}

