#include "rv_declarations.h"
#define RV_MAX_INPUTS 2
#include "rv_inputs.c"
/*** global declarations side 0: ***/
int  rvs0_rv_getint();
char  rvs0_rv_getchar();
void  rvs0_swap(char  *a, char  *b);
char  rvs0_gcd(char  a, char  b);
void  rvs0_simplify(char  *numerator_p, char  *denominator_p);
char  chk0_main();
unsigned char  rvs0_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval);
unsigned char  rvs0_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_8);

/*** global declarations side 1: ***/
int  rvs1_rv_getint();
char  rvs1_rv_getchar();
void  rvs1_swap(char  *a, char  *b);
char  rvs1_gcd(char  a, char  b);
void  rvs1_simplify(char  *numerator_p, char  *denominator_p);
char  chk1_main();
unsigned char  rvs1_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval);
unsigned char  rvs1_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_9);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
char  rvs0_gcd(char  a, char  b)
{
  char  rvretval = 0;

  {
    rvs0_Loop_gcd_while1(&a,&b,&rvretval);
  }

  return b;
}

void  rvs0_simplify(char  *numerator_p, char  *denominator_p)
{
  char  tmp = rvs0_gcd(*numerator_p,*denominator_p);

  *numerator_p = *numerator_p / tmp;
  *denominator_p = *denominator_p / tmp;
}

char  chk0_main()
{
  char  a;
  char  b;

  a = rvs0_rv_getchar();
  b = rvs0_rv_getchar();
  rvs0_simplify(&a,&b);
  return 0;
}


/*** Functions side 1: ***/
char  rvs1_gcd(char  a, char  b)
{
  char  rvretval = 0;

  {
    rvs1_Loop_gcd_while1(&a,&b,&rvretval);
  }

  return b - 1;
}

void  rvs1_simplify(char  *numerator_p, char  *denominator_p)
{
  char  tmp = rvs1_gcd(*numerator_p,*denominator_p);

  *numerator_p = *numerator_p / ++tmp;
  *denominator_p = *denominator_p / tmp;
}

char  chk1_main()
{
  char  b;
  char  a;

  a = 0 + rvs1_rv_getchar();
  b = rvs1_rv_getchar();
  rvs1_simplify(&a,&b);
  return 0;
}


/* Implementations of the uninterpreted functions: */

  /* Declarations of the CBMC uninterpreted functions */
char  __CPROVER_uninterpreted_2_rvp_a(char , char );
char  __CPROVER_uninterpreted_2_rvp_b(char , char );
unsigned char  __CPROVER_uninterpreted_2_retval(char , char );

  /* CBMC-UF side 0: */ 
unsigned char  rvs0_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval)
{
  unsigned char  retval;

  /* Declarations: */
  char  rv_D18_0;	/* Generated by:  gen_side0_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:327*/
  char  rv_D19_0;	/* Generated by:  gen_side0_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc(601)(326)/ gen_safe_alloc/ rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (rvp_a== 0) {
  rvp_a = &rv_D18_0;	/* Generated by:  gen_side0_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:332*/
  }
  if (rvp_b== 0) {
  rvp_b = &rv_D19_0;	/* Generated by:  gen_side0_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc(601)(326)/ gen_safe_alloc/ rv_temps.cpp:332*/
  }

  /* Each output is assigned a UF:*/
  *rvp_a= __CPROVER_uninterpreted_2_rvp_a(*rvp_a, *rvp_b);
  *rvp_b= __CPROVER_uninterpreted_2_rvp_b(*rvp_a, *rvp_b);
  retval= __CPROVER_uninterpreted_2_retval(*rvp_a, *rvp_b);

  return retval;
}


  /* CBMC-UF side 1: */ 
unsigned char  rvs1_Loop_gcd_while1(char  *rvp_a, char  *rvp_b, char  *rvp_rvretval)
{
  unsigned char  retval;

  /* Declarations: */
  char  rv_D20_0;	/* Generated by:  gen_side1_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:327*/
  char  rv_D21_0;	/* Generated by:  gen_side1_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc(601)(326)/ gen_safe_alloc/ rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (rvp_a== 0) {
  rvp_a = &rv_D20_0;	/* Generated by:  gen_side1_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc/ rv_temps.cpp:332*/
  }
  if (rvp_b== 0) {
  rvp_b = &rv_D21_0;	/* Generated by:  gen_side1_cbmc_uf(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)/ protect_pointer [op=9](613)(379)(608)(613)(379)(601)(326)/ gen_safe_alloc(601)(326)/ gen_safe_alloc/ rv_temps.cpp:332*/
  }

  /* Each output is assigned a UF:*/
  *rvp_a= __CPROVER_uninterpreted_2_rvp_a(*rvp_a, *rvp_b);
  *rvp_b= __CPROVER_uninterpreted_2_rvp_b(*rvp_a, *rvp_b);
  retval= __CPROVER_uninterpreted_2_retval(*rvp_a, *rvp_b);

  return retval;
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  char  retval0;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/
  char  retval1;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/


  /* Assume input args are equal: */ 

  /* run each side's main() */
  retval0 = chk0_main();
  retval1 = chk1_main();
  /* Assertions: */

  /* Compare return values: */ 
  assert( retval0 == retval1 );	/* Generated by:  gen_main(608)(613)(379)(309)/ rv_temps.cpp:352*/

  /* Compare output args: */ 


  return 0;
}
