#include "rv_declarations.h"

/*** global declarations side 0: ***/
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
int  chk0_A(int  m, int  n);
int  rvs0_main();
int  rvs0_A(int  m, int  n);
void  __CPROVER_assume(_Bool  rv_arg_2);

/*** global declarations side 1: ***/
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
int  chk1_A(int  m, int  n);
int  rvs1_main();
int  rvs1_A(int  m, int  n);
void  __CPROVER_assume(_Bool  rv_arg_3);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  rvs0_A(int  m, int  n);
int  chk0_A(int  m, int  n)
{
  if (m == 0)
    return n + 1;
  if (m > 0 && n == 0)
    return rvs0_A(m - 1,1);
  return rvs0_A(m - 1,rvs0_A(m,n - 1));
}


/*** Functions side 1: ***/
int  rvs1_A(int  m, int  n);
int  chk1_A(int  m, int  n)
{
  if (m > 0 && n == 0)
    return rvs1_A(m - 1,1);
  if (m == 0)
    return n + 1;
  return rvs1_A(m - 1,rvs1_A(m,n - 1));
}


  /* Declarations of the CBMC uninterpreted functions */
int  __CPROVER_uninterpreted_retval(int , int );

  /* CBMC-UF side 0: */ 
int  rvs0_A(int  m, int  n)
{
  int  retval;

  /* Declarations: */


  /* Each output is assigned a UF:*/
  retval= __CPROVER_uninterpreted_retval(m, n);

  return retval;
}


  /* CBMC-UF side 1: */ 
int  rvs1_A(int  m, int  n)
{
  int  retval;

  /* Declarations: */


  /* Each output is assigned a UF:*/
  retval= __CPROVER_uninterpreted_retval(m, n);

  return retval;
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  int  retval0;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/
  int  retval1;	/* Generated by:  gen_retval_declarations/ rv_temps.cpp:269*/
  int  rvs0_m;	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  rvs1_m;	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  rvs0_n;	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/
  int  rvs1_n;	/* Generated by:  gen_arg_decl(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)(107)/ gen_decl_low(148)/ rv_temps.cpp:274*/

  /* output: */
  /* output: */
  /* Allocations for side 0: */
  /* Allocations for side 1: */

  /* Assume input args are equal: */ 
  rvs0_m = rvs1_m;	/* Generated by:  gen_args_equality(608)(613)(379)(293)/ rv_temps.cpp:362*/
  rvs0_n = rvs1_n;	/* Generated by:  gen_args_equality(608)(613)(379)(293)(608)(613)(379)(293)/ rv_temps.cpp:362*/

  /* run each side's main() */
  retval0 = chk0_A(rvs0_m, rvs0_n);
  retval1 = chk1_A(rvs1_m, rvs1_n);
  /* Assertions: */

  /* Compare return values: */ 
  assert( retval0 == retval1 );	/* Generated by:  gen_main(608)(613)(379)(309)/ rv_temps.cpp:352*/

  /* Compare output args: */ 


  return 0;
}
