#include "rv_declarations.h"
#define RV_MAX_INPUTS 2
#include "rv_inputs.c"
/*** global declarations side 0: ***/
short  rvs0_rv_div_short__short_(short  x, short  y);
short  rvs0_rv_mod_short__short_(short  x, short  y);
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
int  rvs0_rv_getint();
char  rvs0_rv_getchar();
void  rvs0_swap(short  *a, short  *b);
short  rvs0_gcd(short  a, short  b);
void  rvs0_simplify(short  *numerator_p, short  *denominator_p);
short  rvs0_main();
void  rvs0_swap(short  *a, short  *b);
unsigned char  chk0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
unsigned char  rvs0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_2);

/*** global declarations side 1: ***/
short  rvs1_rv_div_short__short_(short  x, short  y);
short  rvs1_rv_mod_short__short_(short  x, short  y);
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
int  rvs1_rv_getint();
char  rvs1_rv_getchar();
void  rvs1_swap(short  *a, short  *b);
short  rvs1_gcd(short  a, short  b);
void  rvs1_simplify(short  *numerator_p, short  *denominator_p);
short  rvs1_main();
void  rvs1_swap(short  *a, short  *b);
unsigned char  chk1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
unsigned char  rvs1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_3);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
unsigned char  rvs0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
unsigned char  chk0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  if (!(*rvp_a != 0))
    return 0;
  {
    *rvp_b = rvs0_rv_mod_short__short_(*rvp_b,*rvp_a);
    rvs0_swap(&*rvp_a,&*rvp_b);
  }

  {
    return rvs0_Loop_gcd_while1(rvp_a,rvp_b,rvp_rvretval);
  }

  return 0;
}


/*** Functions side 1: ***/
unsigned char  rvs1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval);
unsigned char  chk1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  if (!(*rvp_a != 0))
    return 0;
  {
    *rvp_b = rvs1_rv_mod_short__short_(*rvp_b,*rvp_a);
    rvs1_swap(&*rvp_a,&*rvp_b);
    *rvp_a = *rvp_a;
  }

  {
    return rvs1_Loop_gcd_while1(rvp_a,rvp_b,rvp_rvretval);
  }

  return 0;
}


/* Implementations of the uninterpreted functions: */

  /* Declarations of the CBMC uninterpreted functions */
short  __CPROVER_uninterpreted_retval(short , short );

  /* CBMC-UF side 0: */ 
short  rvs0_rv_mod_short__short_(short  x, short  y)
{
  short  retval;

  /* Declarations: */


  /* Each output is assigned a UF:*/
  retval= __CPROVER_uninterpreted_retval(x, y);
__CPROVER_assume(1);
  return retval;
}


  /* CBMC-UF side 1: */ 
short  rvs1_rv_mod_short__short_(short  x, short  y)
{
  short  retval;

  /* Declarations: */


  /* Each output is assigned a UF:*/
  retval= __CPROVER_uninterpreted_retval(x, y);
__CPROVER_assume(1);
  return retval;
}


  /* Declarations of the CBMC uninterpreted functions */
short  __CPROVER_uninterpreted_1_a(short , short );
short  __CPROVER_uninterpreted_1_b(short , short );

  /* CBMC-UF side 0: */ 
void  rvs0_swap(short  *a, short  *b)
{
  /* Declarations: */
  short  rv_D0_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  short  rv_D1_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (a== 0) {
  a = &rv_D0_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }
  if (b== 0) {
  b = &rv_D1_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }

  /* Each output is assigned a UF:*/
  *a= __CPROVER_uninterpreted_1_a(*a, *b);
  *b= __CPROVER_uninterpreted_1_b(*a, *b);
__CPROVER_assume(1);
}


  /* CBMC-UF side 1: */ 
void  rvs1_swap(short  *a, short  *b)
{
  /* Declarations: */
  short  rv_D2_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  short  rv_D3_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (a== 0) {
  a = &rv_D2_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }
  if (b== 0) {
  b = &rv_D3_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }

  /* Each output is assigned a UF:*/
  *a= __CPROVER_uninterpreted_1_a(*a, *b);
  *b= __CPROVER_uninterpreted_1_b(*a, *b);
__CPROVER_assume(1);
}


  /* Declarations of the CBMC uninterpreted functions */
short  __CPROVER_uninterpreted_2_rvp_a(short , short , short );
short  __CPROVER_uninterpreted_2_rvp_b(short , short , short );
unsigned char  __CPROVER_uninterpreted_2_retval(short , short , short );

  /* CBMC-UF side 0: */ 
unsigned char  rvs0_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  unsigned char  retval;

  /* Declarations: */
  short  rv_D4_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  short  rv_D5_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  short  rv_D6_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (rvp_a== 0) {
  rvp_a = &rv_D4_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }
  if (rvp_b== 0) {
  rvp_b = &rv_D5_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }
  if (rvp_rvretval== 0) {
  rvp_rvretval = &rv_D6_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }

  /* Each output is assigned a UF:*/
  *rvp_a= __CPROVER_uninterpreted_2_rvp_a(*rvp_a, *rvp_b, *rvp_rvretval);
  *rvp_b= __CPROVER_uninterpreted_2_rvp_b(*rvp_a, *rvp_b, *rvp_rvretval);
  retval= __CPROVER_uninterpreted_2_retval(*rvp_a, *rvp_b, *rvp_rvretval);
__CPROVER_assume(1);
  return retval;
}


  /* CBMC-UF side 1: */ 
unsigned char  rvs1_Loop_gcd_while1(short  *rvp_a, short  *rvp_b, short  *rvp_rvretval)
{
  unsigned char  retval;

  /* Declarations: */
  short  rv_D7_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  short  rv_D8_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  short  rv_D9_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (rvp_a== 0) {
  rvp_a = &rv_D7_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }
  if (rvp_b== 0) {
  rvp_b = &rv_D8_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }
  if (rvp_rvretval== 0) {
  rvp_rvretval = &rv_D9_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)/ RVGen::protect_pointer [op=9](626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }

  /* Each output is assigned a UF:*/
  *rvp_a= __CPROVER_uninterpreted_2_rvp_a(*rvp_a, *rvp_b, *rvp_rvretval);
  *rvp_b= __CPROVER_uninterpreted_2_rvp_b(*rvp_a, *rvp_b, *rvp_rvretval);
  retval= __CPROVER_uninterpreted_2_retval(*rvp_a, *rvp_b, *rvp_rvretval);
__CPROVER_assume(1);
  return retval;
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  unsigned char  retval0;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/
  unsigned char  retval1;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/
  short  *rvs0_rvp_a;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  short  *rvs1_rvp_a;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  short  *rvs0_rvp_b;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  short  *rvs1_rvp_b;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  short  *rvs0_rvp_rvretval;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  short  *rvs1_rvp_rvretval;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  short  rv_D10_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  short  rv_D11_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  short  rv_D12_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  short  rv_D13_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  short  rv_D14_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  short  rv_D15_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/

  /* output: */
  /* output: */
  /* output: */
  /* Allocations for side 0: */
  rvs0_rvp_a = &rv_D10_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  rvs0_rvp_b = &rv_D11_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  rvs0_rvp_rvretval = &rv_D12_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  /* Allocations for side 1: */
  rvs1_rvp_a = &rv_D13_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  rvs1_rvp_b = &rv_D14_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  rvs1_rvp_rvretval = &rv_D15_0;	/* Generated by:  RVMainGen::gen_arg_alloc_side(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/

  /* Assume input args are equal: */ 
  *rvs0_rvp_a = *rvs1_rvp_a;	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=4](626)(392)(306)/ c:\newrvt\rv_temps.cpp:362*/
  *rvs0_rvp_b = *rvs1_rvp_b;	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)/ c:\newrvt\rv_temps.cpp:362*/
  *rvs0_rvp_rvretval = *rvs1_rvp_rvretval;	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)(621)/ RVGen::protect_pointer [op=4](626)(392)(306)/ c:\newrvt\rv_temps.cpp:362*/

  /* run each side's main() */
  retval0 = chk0_Loop_gcd_while1(rvs0_rvp_a, rvs0_rvp_b, rvs0_rvp_rvretval);
  retval1 = chk1_Loop_gcd_while1(rvs1_rvp_a, rvs1_rvp_b, rvs1_rvp_rvretval);
  /* Assertions: */

  /* Compare return values: */ 
  assert( retval0 == retval1 );	/* Generated by:  RVMainGen::gen_main(621)(626)(392)(322)/ c:\newrvt\rv_temps.cpp:352*/

  /* Compare output args: */ 
  assert( *rvs0_rvp_a == *rvs1_rvp_a );	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=6](626)(392)(322)/ c:\newrvt\rv_temps.cpp:352*/
  assert( *rvs0_rvp_b == *rvs1_rvp_b );	/* Generated by:  RVMainGen::gen_args_equality(621)/ RVGen::protect_pointer [op=6](626)(392)(322)(621)/ RVGen::protect_pointer [op=6](626)(392)(322)/ c:\newrvt\rv_temps.cpp:352*/


  return 0;
}
