#include "rv_declarations.h"

/*** global declarations of both sides: ***/

/*** global declarations side 0: ***/
int  rvs0_checkInput(int  n);
int  chk0_f(int  n);
int  rvs0_main();
int  rvs0_checkInput(int  n);
unsigned char  rvs0_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
unsigned char  rvs0_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_2);

/*** global declarations side 1: ***/
int  rvs1_checkInput(int  n);
int  chk1_f(int  n);
int  rvs1_main();
int  rvs1_checkInput(int  n);
unsigned char  rvs1_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
unsigned char  rvs1_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval);
void  __CPROVER_assume(_Bool  rv_arg_3);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  chk0_f(int  n)
{
  int  rvretval = 0;

  if (rvs0_checkInput(n))
  {
    return 0;
  }

  int  i;
  int  sum = 0;
  {
    i = 1;
    rvs0_Loop_f_for1(n,&i,&sum,&rvretval);
  }

  return sum;
}


/*** Functions side 1: ***/
int  chk1_f(int  n)
{
  int  rvretval = 0;

  if (rvs1_checkInput(n))
  {
    return 0;
  }

  int  sum = 0;
  {
    int  i = 1;

    {
      rvs1_Loop_f_for1(n,&i,&sum,&rvretval);
    }

  }

  return sum;
}


/* Implementations of the uninterpreted functions: */

  /* Declarations of the CBMC uninterpreted functions */
int  __CPROVER_uninterpreted_rvp_i(int , int , int );
int  __CPROVER_uninterpreted_rvp_sum(int , int , int );
unsigned char  __CPROVER_uninterpreted_retval(int , int , int );

  /* CBMC-UF side 0: */ 
unsigned char  rvs0_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval)
{
  unsigned char  retval;

  /* Declarations: */
  int  rv_D0_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(615)(620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)(620)(386)(608)(333)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  int  rv_D1_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(615)(620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)(620)(386)(608)(333)/ RVTemp::gen_safe_alloc(608)(333)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (rvp_i== 0) {
  rvp_i = &rv_D0_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(615)(620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)(620)(386)(608)(333)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }
  if (rvp_sum== 0) {
  rvp_sum = &rv_D1_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(615)(620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)(620)(386)(608)(333)/ RVTemp::gen_safe_alloc(608)(333)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }

  /* Each output is assigned a UF:*/
  *rvp_i= __CPROVER_uninterpreted_rvp_i(n, *rvp_i, *rvp_sum);
  *rvp_sum= __CPROVER_uninterpreted_rvp_sum(n, *rvp_i, *rvp_sum);
  retval= __CPROVER_uninterpreted_retval(n, *rvp_i, *rvp_sum);

  return retval;
}


  /* CBMC-UF side 1: */ 
unsigned char  rvs1_Loop_f_for1(int  n, int  *rvp_i, int  *rvp_sum, int  *rvp_rvretval)
{
  unsigned char  retval;

  /* Declarations: */
  int  rv_D2_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(615)(620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)(620)(386)(608)(333)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  int  rv_D3_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(615)(620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)(620)(386)(608)(333)/ RVTemp::gen_safe_alloc(608)(333)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (rvp_i== 0) {
  rvp_i = &rv_D2_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(615)(620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)(620)(386)(608)(333)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }
  if (rvp_sum== 0) {
  rvp_sum = &rv_D3_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(615)(620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)/ RVGen::protect_pointer [op=9](620)(386)(615)(620)(386)(608)(333)/ RVTemp::gen_safe_alloc(608)(333)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }

  /* Each output is assigned a UF:*/
  *rvp_i= __CPROVER_uninterpreted_rvp_i(n, *rvp_i, *rvp_sum);
  *rvp_sum= __CPROVER_uninterpreted_rvp_sum(n, *rvp_i, *rvp_sum);
  retval= __CPROVER_uninterpreted_retval(n, *rvp_i, *rvp_sum);

  return retval;
}


  /* Declarations of the CBMC uninterpreted functions */
int  __CPROVER_uninterpreted_1_retval(int );

  /* CBMC-UF side 0: */ 
int  rvs0_checkInput(int  n)
{
  int  retval;

  /* Declarations: */


  /* Each output is assigned a UF:*/
  retval= __CPROVER_uninterpreted_1_retval(n);

  return retval;
}


  /* CBMC-UF side 1: */ 
int  rvs1_checkInput(int  n)
{
  int  retval;

  /* Declarations: */


  /* Each output is assigned a UF:*/
  retval= __CPROVER_uninterpreted_1_retval(n);

  return retval;
}

