#include "rv_declarations.h"

/*** global declarations side 0: ***/
int  chk0_f(int  a);
int  rvs0_main();
int  rvs0_f(int  a);
void  __CPROVER_assume(_Bool  rv_arg_2);

/*** global declarations side 1: ***/
int  chk1_f(int  x);
int  rvs1_main();
int  rvs1_f(int  x);
void  __CPROVER_assume(_Bool  rv_arg_3);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  rvs0_f(int  a);
int  chk0_f(int  a)
{
  if (a > 1)
  {
    a = (a & 1) ? (3 * a + 1) : (a / 2);
    return rvs0_f(a);
  }

  return a;
}


/*** Functions side 1: ***/
int  rvs1_f(int  x);
int  chk1_f(int  x)
{
  int  n;

  if (x <= 1)
  {
    return x;
  }

  n = x >> 1;
  if (x % 2)
  {
    n = 6 * n + 4;
  }

  return rvs1_f(n);
}


typedef struct rv_UF_f_struct_tag {
  int  in_a;	/* Generated by:  RVUFGen::gen_uf_item_decl(114)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  out_retval;	/* Generated by:  RVUFGen::gen_uf_array(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  _Bool reach_equiv_flag;
} rv_UF_f_struct;
#define rv_UF_K_f 5
rv_UF_f_struct rv_UF_f_array[rv_UF_K_f];
int rv_UF_f_count[2] = {0,0};


 /*** uninterpreted function side 0: ***/ 
  /* Declarations: */


int  rvs0_f(int  a)
{
  int  retval;

  /* save values of input arguments: */
  rv_UF_f_array[rv_UF_f_count[0]]. = a;	/* Generated by:  RVUFGen::gen_side0_uf(621)(626)(392)(306)/ c:\newrvt\rv_temps.cpp:362*/
  /* save values of input globals: */

  /* generate and save values of output arguments and globals: */
  rv_UF_f_array[rv_UF_f_count[0]]. = retval = (int )nondet_long();	/* Generated by:  RVUFGen::gen_side0_uf(621)(626)(392)(306)(621)(626)(392)(276)/ c:\newrvt\rv_temps.cpp:412*/
  rv_UF_f_count[0]++;

  return retval;
}


/*** uninterpreted function side 1: ***/ 
int  rvs1_f(int  x)
{
  int  retval;

  _Bool found = 0;
  _Bool equal = 1;
  int found_ind = -1;
  int rv_uf_ind = rv_UF_f_count[0]-1;
  for(; rv_uf_ind >= 0; rv_uf_ind--) {
    equal = (rv_UF_f_array[rv_uf_ind]. == x);	/* Generated by:  RVUFGen::gen_side1_uf(621)(626)(392)(285)/ c:\newrvt\rv_temps.cpp:427*/
    if( equal ) { 
      found = 1;
      found_ind = rv_uf_ind;
		      rv_UF_f_array[rv_uf_ind].reach_equiv_flag = 1;
    }
		equal = 1;
  }

  if( found ) /* input values were found among the saved values */
  {
   /* Sides 0 and 1 are not known to be partially equivalent.
    * Returning some results unrelated to the side 0: */
  retval = (int )nondet_long();	/* Generated by:  RVUFGen::gen_input_not_found_case(621)(626)(392)(256)/ c:\newrvt\rv_temps.cpp:383*/

  } else {

    /* Assert reach-equivalence: side 0 and 1 inputs are equal.*/
    assert( 0 );

  }
  rv_UF_f_count[1]++;

  return retval;
}

void rvt_token_initialize_mutual_termination_tokens_f(){
	int rvt_token_i = 0;
		for (rvt_token_i = 0 ; rvt_token_i < rv_UF_K_f ; rvt_token_i++){
			rvt_token_f_call_mark_array0[rvt_token_i] = 0;
			rvt_token_f_call_mark_array1[rvt_token_i] = 0;
		}
		rvt_token_f_count = 0;
		rvt_token_f_first_call_to_uf_flag = 0;

}





void rv_init()
{
}


void rv_check()
{
  /* check reach-equivalence of the inputs for each uninterpreted function: */
  int i;

  /* checking reach-equivalence of all the inputs of array rv_UF_f_array : */
  for (i = rv_UF_f_count[0] - 1; i >= 0; --i)
    assert( rv_UF_f_array[i].reach_equiv_flag );
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  int  retval0;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/
  int  retval1;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/
  int  rvs0_a;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  rvs1_x;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/


  /* output: */
  /* Allocations for side 0: */
  /* Allocations for side 1: */

  rv_init();

  /* Assume input args are equal: */ 
  rvs0_a = rvs1_x;	/* Generated by:  RVMainGen::gen_args_equality(621)(626)(392)(306)/ c:\newrvt\rv_temps.cpp:362*/

  /* run each side's main() */
  retval0 = chk0_f(rvs0_a);
  retval1 = chk1_f(rvs1_x);

  rv_check();

  return 0;
}
