#include "rv_declarations.h"

/*** global declarations of both sides: ***/
typedef int  pid_t;
typedef unsigned int  size_t;
typedef unsigned char  u_char;
typedef unsigned long  ulong;
typedef unsigned short  ushort;
typedef unsigned int  uint;
typedef unsigned int  off_t;
typedef unsigned int  mode_t;
typedef unsigned int  u_int;
typedef int  uid_t;

/*** global declarations side 0: ***/
typedef int  (*rvs0_rvt_FuncPtrSubst_int__const_void_ptr_const_void_ptr)(void  *rv_arg_0, void  *rv_arg_1);
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
void  rvs0_exit(int  status);
char  *rvs0_getenv(char  *name);
int  rvs0_system(char  *string);
void  rvs0_abort();
void  *calloc(size_t  nmemb, size_t  size);
void  *malloc(size_t  size);
void  free(void  *ptr);
void  *realloc(void  *ptr, size_t  size);
int  rvs0_atoi(char  *nptr);
long  rvs0_atol(char  *nptr);
long long  rvs0_atoll(char  *nptr);
long long  rvs0_atoq(char  *nptr);
float  rvs0_atof(char  *nptr);
int  rvs0_rand();
void  rvs0_srand(unsigned int  seed);
long  rvs0_random();
void  rvs0_srandom(unsigned int  seed);
char  *rvs0_initstate(unsigned int  seed, char  *state, size_t  n);
char  *rvs0_setstate(char  *state);
int  rvs0_mkstemp(char  *temp);
void  rvs0_qsort(void  *base, size_t  num, size_t  width, rvs0_rvt_FuncPtrSubst_int__const_void_ptr_const_void_ptr  fncompare);
int  rvs0_F(int  *n);
int  chk0_main();
int  rvs0_F(int  *n);
void  __CPROVER_assume(_Bool  rv_arg_8);

/*** global declarations side 1: ***/
typedef int  (*rvs1_rvt_FuncPtrSubst_int__const_void_ptr_const_void_ptr)(void  *rv_arg_2, void  *rv_arg_3);
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
void  rvs1_exit(int  status);
char  *rvs1_getenv(char  *name);
int  rvs1_system(char  *string);
void  rvs1_abort();
void  *calloc(size_t  nmemb, size_t  size);
void  *malloc(size_t  size);
void  free(void  *ptr);
void  *realloc(void  *ptr, size_t  size);
int  rvs1_atoi(char  *nptr);
long  rvs1_atol(char  *nptr);
long long  rvs1_atoll(char  *nptr);
long long  rvs1_atoq(char  *nptr);
float  rvs1_atof(char  *nptr);
int  rvs1_rand();
void  rvs1_srand(unsigned int  seed);
long  rvs1_random();
void  rvs1_srandom(unsigned int  seed);
char  *rvs1_initstate(unsigned int  seed, char  *state, size_t  n);
char  *rvs1_setstate(char  *state);
int  rvs1_mkstemp(char  *temp);
void  rvs1_qsort(void  *base, size_t  num, size_t  width, rvs1_rvt_FuncPtrSubst_int__const_void_ptr_const_void_ptr  fncompare);
int  rvs1_F(int  *n);
int  chk1_main();
int  rvs1_F(int  *n);
void  __CPROVER_assume(_Bool  rv_arg_9);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  chk0_main()
{
  int  i;
  int  out = 0;
  int  *p = (int *) (malloc(sizeof(int ) ));

  *p = 10;
  out = rvs0_F(p);
  return out;
}


/*** Functions side 1: ***/
int  chk1_main()
{
  int  i;
  int  out = 0;
  int  *p = (int *) (malloc(sizeof(int ) ));

  *p = 10;
  out = rvs1_F(p);
  *p = 2;
  return out;
}


/* Implementations of the uninterpreted functions: */
#define rv_UF_K_F 5
//Recording arrays for local parameter input
int  rvt_token_F_n[rv_UF_K_F];

//Recording arrays for global input

//Output arrays for local input
int  rvt_token_F_n_output[rv_UF_K_F];


//Output arrays for global input

//Output array for function output
int  rvt_token_F_retval_output[rv_UF_K_F];

int  rvt_token_F_call_mark_array0[rv_UF_K_F];
int  rvt_token_F_call_mark_array1[rv_UF_K_F];
int  rvt_token_F_count;
_Bool  rvt_token_F_first_call_to_uf_flag;

 /*** uninterpreted function side 0: ***/ 
int  rvs0_F(int  *n)
{
  int  retval;

 /* Zeroing both mark arrays and count variable for unitrv mutual termination check */
  /* save values of input arguments: */
	rvt_token_F_n[rvt_token_F_count] = *n;
  /* save values of input globals: */

  /* generate and save values of output arguments and globals: */
  rvt_token_F_n_output[rvt_token_F_count] = *n = (int )nondet_long();	/* Generated by:  RVReUfGen::gen_unitrv_side0_uf(615)/ RVGen::protect_pointer [op=2](620)(386)(267)/ c:\newrvt\rv_temps.cpp:420*/

  /* generate and save value for the functino output : */
  rvt_token_F_retval_output[rvt_token_F_count] = retval = (int )nondet_long();	/* Generated by:  RVReUfGen::gen_unitrv_side0_uf(615)/ RVGen::protect_pointer [op=2](620)(386)(267)(615)(620)(386)(267)/ c:\newrvt\rv_temps.cpp:420*/
	rvt_token_F_call_mark_array0[rvt_token_F_count] = 1;
	rvt_token_F_count++;
  return retval;
}


/*** uninterpreted function side 1: ***/ 
int  rvs1_F(int  *n)
{
  int  retval;

  _Bool found = 0;
  _Bool equal = 1;
  int found_ind = -1;
  int rv_uf_ind = rvt_token_F_count-1;
  for(; rv_uf_ind >= 0; rv_uf_ind--) {
		equal = equal && *n == rvt_token_F_n[rv_uf_ind];
    if( equal ) { 
      found = 1;
      found_ind = rv_uf_ind;
		rvt_token_F_call_mark_array1[rv_uf_ind] = 1;
    }
		equal = 1;
  }

  if( found ) /* input values were found among the saved values */
  {
   /* Sides 0 and 1 are not known to be partially equivalent.
    * Returning some results unrelated to the side 0: */
  int  rv_D0_0;	/* Generated by:  RVReUfGen::gen_unitrv_input_found_case(615)/ RVGen::protect_pointer [op=1](480)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/
  n = &rv_D0_0;	/* Generated by:  RVReUfGen::gen_unitrv_input_found_case(615)/ RVGen::protect_pointer [op=1](480)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  *n = (int )nondet_long();	/* Generated by:  RVReUfGen::gen_unitrv_input_found_case(615)/ RVGen::protect_pointer [op=1](480)/ RVTemp::gen_safe_alloc(620)(386)(250)/ c:\newrvt\rv_temps.cpp:383*/
  retval = (int )nondet_long();	/* Generated by:  RVReUfGen::gen_unitrv_input_found_case(615)/ RVGen::protect_pointer [op=1](480)/ RVTemp::gen_safe_alloc(620)(386)(250)(615)(620)(386)(250)/ c:\newrvt\rv_temps.cpp:383*/

  } else {

    /* Assert reach-equivalence: side 0 and 1 inputs are equal.*/
    assert( 0 );

  }

  return retval;
}

void rvt_token_initialize_mutual_termination_tokens_F(){
	int rvt_token_i = 0;
		for (rvt_token_i = 0 ; rvt_token_i < rv_UF_K_F ; rvt_token_i++){
			rvt_token_F_call_mark_array0[rvt_token_i] = 0;
			rvt_token_F_call_mark_array1[rvt_token_i] = 0;
		}
		rvt_token_F_count = 0;
		rvt_token_F_first_call_to_uf_flag = 0;

}
