#include "rv_declarations.h"

/*** global declarations side 0: ***/
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
void  __CPROVER_assume(_Bool  rv_arg_0);
void  assert(_Bool  rv_arg_1);
void  rvs0_bubble_sort(int  *a, int  sz);
int  rvs0_a[5];
void  rvs0_bubble_sort(int  *a, int  sz);
int  chk0_init_array(int  n);
int  rvs0_main();
unsigned char  rvs0_Loop_bubble_sort_for1(int  *a, int  sz, int  *rvp_i);
unsigned char  rvs0_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
void  __CPROVER_assume(_Bool  rv_arg_10);

/*** global declarations side 1: ***/
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
void  __CPROVER_assume(_Bool  rv_arg_2);
void  assert(_Bool  rv_arg_3);
void  rvs1_bubble_sort(int  *a, int  sz);
int  rvs1_a[5];
void  rvs1_bubble_sort(int  *a, int  sz);
int  chk1_init_array(int  n);
int  rvs1_main();
unsigned char  rvs1_Loop_bubble_sort_for1(int  *a, int  sz, int  *rvp_i);
unsigned char  rvs1_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
void  __CPROVER_assume(_Bool  rv_arg_11);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  chk0_init_array(int  n)
{
  int  j = 5;

  rvs0_a[0] = 17;
  rvs0_a[1] = 9;
  rvs0_a[2] = 7;
  rvs0_a[3] = 11;
  rvs0_a[4] = 16;
  j = 17;
  return 0;
}


/*** Functions side 1: ***/
int  chk1_init_array(int  n)
{
  *(rvs1_a + 0) = 17;
  *(rvs1_a + 1) = 9;
  *(rvs1_a + 2) = 7;
  *(rvs1_a + 3) = 11;
  *(rvs1_a + 4) = 16;
  return 0;
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  int  retval0;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/
  int  retval1;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/
  int  rvs0_n;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/
  int  rvs1_n;	/* Generated by:  RVMainGen::gen_arg_decl(110)/ RVGen::gen_decl_low(151)(110)/ RVGen::gen_decl_low(151)/ c:\newrvt\rv_temps.cpp:274*/

  /* output: */
  /* Allocations for side 0: */
  /* Allocations for side 1: */

  /* Assume input args are equal: */ 
  rvs0_n = rvs1_n;	/* Generated by:  RVMainGen::gen_args_equality(621)(626)(392)(306)/ c:\newrvt\rv_temps.cpp:362*/

  /* Begin: Assume globals are equal: */ 
//nondet values for side 0:
  RVT_NONDET_ARRAY(rvs0_a,5);	/* Generated by:  RVMainGen::gen_equal_nondet_globals(621)(626)(392)(254)/ c:\newrvt\rv_temps.cpp:399*/
//alloc for side 1:
//copy leaves from side 0 to 1:
  RVT_COPY_ARRAY(rvs1_a,rvs0_a, 5);	/* Generated by:  RVMainGen::gen_equal_nondet_globals(621)(626)(392)(254)(614)(621)(626)(392)(291)/ c:\newrvt\rv_temps.cpp:368*/
//until here

  /* End: Assume globals are equal: */ 
// for asserting global equality:

  /* run each side's main() */
  retval0 = chk0_init_array(rvs0_n);
  retval1 = chk1_init_array(rvs1_n);
  /* Assertions: */

  /* Compare return values: */ 
  assert( retval0 == retval1 );	/* Generated by:  RVMainGen::gen_main(621)(626)(392)(322)/ c:\newrvt\rv_temps.cpp:352*/

  /* Compare output args: */ 
  RVT_ASSERT_EQ_ARRAY(rvs0_a,rvs1_a,5 );	/* Generated by:  RVMainGen::gen_globals_check_output(621)(626)(392)(316)/ c:\newrvt\rv_temps.cpp:404*/


  return 0;
}
