#include "rv_declarations.h"

/*** global declarations side 0: ***/
float  rvs0_rv_mult(float  x, float  y);
float  rvs0_rv_div(float  x, float  y);
int  rvs0_rv_mod(int  x, int  y);
void  __CPROVER_assume(_Bool  rv_arg_0);
void  assert(_Bool  rv_arg_1);
void  rvs0_bubble_sort(int  *a, int  sz);
int  rvs0_a[5];
void  rvs0_bubble_sort(int  *a, int  sz);
int  rvs0_init_array(int  n);
int  chk0_main();
unsigned char  rvs0_Loop_bubble_sort_for1(int  *a, int  sz, int  *rvp_i);
unsigned char  rvs0_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
void  rvs0_bubble_sort(int  *a, int  sz);
int  rvs0_init_array(int  n);
void  __CPROVER_assume(_Bool  rv_arg_12);

/*** global declarations side 1: ***/
float  rvs1_rv_mult(float  x, float  y);
float  rvs1_rv_div(float  x, float  y);
int  rvs1_rv_mod(int  x, int  y);
void  __CPROVER_assume(_Bool  rv_arg_2);
void  assert(_Bool  rv_arg_3);
void  rvs1_bubble_sort(int  *a, int  sz);
int  rvs1_a[5];
void  rvs1_bubble_sort(int  *a, int  sz);
int  rvs1_init_array(int  n);
int  chk1_main();
unsigned char  rvs1_Loop_bubble_sort_for1(int  *a, int  sz, int  *rvp_i);
unsigned char  rvs1_Loop_bubble_sort_for1_for1(int  *a, int  i, int  *rvp_j);
void  rvs1_bubble_sort(int  *a, int  sz);
int  rvs1_init_array(int  n);
void  __CPROVER_assume(_Bool  rv_arg_13);

/*** end of global declarations side 1: ***/
/*** end of global declarations. ***/

/*** Functions side 0: ***/
int  chk0_main()
{
  int  i;
  int  cmp;

  i = rvs0_init_array(5);
  rvs0_bubble_sort(rvs0_a,5);
  cmp = rvs0_a[0];
  return 0;
}


/*** Functions side 1: ***/
int  chk1_main()
{
  int  i;

  i = rvs1_init_array(5);
  rvs1_bubble_sort(rvs1_a,5);
  return 0;
}


/* Implementations of the uninterpreted functions: */

  /* Declarations of the CBMC uninterpreted functions */
  /* Globals for saving input arrays: */
int  RV_ARR_SAVE_3_rvs0_a_0[5];

int  __CPROVER_uninterpreted_3_rvs0_a(int );
int  __CPROVER_uninterpreted_3_retval(int );
  /* For each array X side X record, an output array. */
int  RV_ARR_OUT_s0_rvs0_a_3_0[5];
int  RV_ARR_OUT_s1_rvs0_a_3_0[5];


  /* CBMC-UF side 0: */ 
int  rvs0_init_array(int  n)
{
  int  retval;

  /* Declarations: */


  static unsigned char rv_call_counter = 0;
  int *RV_ARR_P_s0_rvs0_a;
  int *RV_ARR_P_s1_rvs0_a;
  switch(rv_call_counter) {
    case 0:RV_ARR_P_s0_rvs0_a = RV_ARR_OUT_s0_rvs0_a_3_0; RV_ARR_P_s1_rvs0_a = RV_ARR_OUT_s1_rvs0_a_3_0; RVT_COPY_ARRAY(RV_ARR_SAVE_3_rvs0_a_0, rvs0_a, 5); break;
    default: assert(0);
  }
  rv_call_counter++;
  /* Each output is assigned a UF:*/
  if (__CPROVER_uninterpreted_3_rvs0_a(1))
  {RVT_COPY_ARRAY(rvs0_a, RV_ARR_P_s0_rvs0_a, 5);}
  else
  {RVT_COPY_ARRAY(rvs0_a, RV_ARR_P_s1_rvs0_a, 5);}
  retval= __CPROVER_uninterpreted_3_retval(1);
__CPROVER_assume( (!(n <= 5 && -(n) <= -5 ) || ( retval <= 0 && -(retval) <= 0)));
  return retval;
}


  /* CBMC-UF side 1: */ 
int  rvs1_init_array(int  n)
{
  int  retval;

  /* Declarations: */


  _Bool RV_ARR_EQ_3_rvs1_a;
  static unsigned char rv_call_counter = 0;
  int *RV_ARR_P_s0_rvs1_a;
  int *RV_ARR_P_s1_rvs1_a;
  switch(rv_call_counter) {
    case 0:RV_ARR_P_s0_rvs1_a = RV_ARR_OUT_s0_rvs0_a_3_0; RV_ARR_P_s1_rvs1_a = RV_ARR_OUT_s1_rvs0_a_3_0;   RV_ARR_EQ_3_rvs1_a = __CPROVER_array_equal(rvs1_a,RV_ARR_SAVE_3_rvs0_a_0);  break;
    default: assert(0);
  }
  rv_call_counter++;
  /* Each output is assigned a UF:*/
  if (__CPROVER_uninterpreted_3_rvs0_a(RV_ARR_EQ_3_rvs1_a))
  {RVT_COPY_ARRAY(rvs1_a, RV_ARR_P_s0_rvs1_a, 5);}
  else
  {RVT_COPY_ARRAY(rvs1_a, RV_ARR_P_s1_rvs1_a, 5);}
  retval= __CPROVER_uninterpreted_3_retval(RV_ARR_EQ_3_rvs1_a);
__CPROVER_assume( (!(n <= 5 && -(n) <= -5 ) || ( retval <= 0 && -(retval) <= 0)));
  return retval;
}


  /* Declarations of the CBMC uninterpreted functions */
  /* Globals for saving input arrays: */
int  RV_ARR_SAVE_4_a_0[5];

int  __CPROVER_uninterpreted_4_a(int , int );
  /* For each array X side X record, an output array. */
int  RV_ARR_OUT_s0_a_4_0[5];
int  RV_ARR_OUT_s1_a_4_0[5];


  /* CBMC-UF side 0: */ 
void  rvs0_bubble_sort(int  *a, int  sz)
{
  /* Declarations: */
  int  rv_D16_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)(626)(392)(621)(626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (a== 0) {
  a = &rv_D16_0;	/* Generated by:  RVUFGen::gen_side0_cbmc_uf(621)(626)(392)(621)(626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }

  static unsigned char rv_call_counter = 0;
  int *RV_ARR_P_s0_a;
  int *RV_ARR_P_s1_a;
  switch(rv_call_counter) {
    case 0:RV_ARR_P_s0_a = RV_ARR_OUT_s0_a_4_0; RV_ARR_P_s1_a = RV_ARR_OUT_s1_a_4_0; RVT_COPY_ARRAY(RV_ARR_SAVE_4_a_0, a, 5); break;
    default: assert(0);
  }
  rv_call_counter++;
  /* Each output is assigned a UF:*/
  if (__CPROVER_uninterpreted_4_a(1, sz))
  {RVT_COPY_ARRAY(a, RV_ARR_P_s0_a, 5);}
  else
  {RVT_COPY_ARRAY(a, RV_ARR_P_s1_a, 5);}
__CPROVER_assume( (!(sz <= 5 && -(sz) <= -5 ) || ( 1)));
}


  /* CBMC-UF side 1: */ 
void  rvs1_bubble_sort(int  *a, int  sz)
{
  /* Declarations: */
  int  rv_D17_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)(626)(392)(621)(626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:327*/

  /* Protecting pointers from being NULL-dereferenced: */
  if (a== 0) {
  a = &rv_D17_0;	/* Generated by:  RVUFGen::gen_side1_cbmc_uf(621)(626)(392)(621)(626)(392)(621)(626)(392)(614)(339)/ RVTemp::gen_safe_alloc/ c:\newrvt\rv_temps.cpp:332*/
  }

  _Bool RV_ARR_EQ_4_a;
  static unsigned char rv_call_counter = 0;
  int *RV_ARR_P_s0_a;
  int *RV_ARR_P_s1_a;
  switch(rv_call_counter) {
    case 0:RV_ARR_P_s0_a = RV_ARR_OUT_s0_a_4_0; RV_ARR_P_s1_a = RV_ARR_OUT_s1_a_4_0;   RV_ARR_EQ_4_a = __CPROVER_array_equal(a,RV_ARR_SAVE_4_a_0);  break;
    default: assert(0);
  }
  rv_call_counter++;
  /* Each output is assigned a UF:*/
  if (__CPROVER_uninterpreted_4_a(RV_ARR_EQ_4_a, sz))
  {RVT_COPY_ARRAY(a, RV_ARR_P_s0_a, 5);}
  else
  {RVT_COPY_ARRAY(a, RV_ARR_P_s1_a, 5);}
__CPROVER_assume( (!(sz <= 5 && -(sz) <= -5 ) || ( 1)));
}

  /* now starting main */

int main()
{
  _Bool equal = 1;
  /* Declarations: */
  int  retval0;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/
  int  retval1;	/* Generated by:  RVTemp::gen_retval_declarations/ c:\newrvt\rv_temps.cpp:269*/

  int  rv_nd_RV_ARR_OUT_s0_rvs0_a_3_0[5];
  int  rv_nd_RV_ARR_OUT_s1_rvs0_a_3_0[5];
  int  rv_nd_RV_ARR_OUT_s0_a_4_0[5];
  int  rv_nd_RV_ARR_OUT_s1_a_4_0[5];
  __CPROVER_array_copy(RV_ARR_OUT_s0_rvs0_a_3_0,  rv_nd_RV_ARR_OUT_s0_rvs0_a_3_0);
  __CPROVER_array_copy(RV_ARR_OUT_s1_rvs0_a_3_0,  rv_nd_RV_ARR_OUT_s1_rvs0_a_3_0);
  __CPROVER_array_copy(RV_ARR_OUT_s0_a_4_0,  rv_nd_RV_ARR_OUT_s0_a_4_0);
  __CPROVER_array_copy(RV_ARR_OUT_s1_a_4_0,  rv_nd_RV_ARR_OUT_s1_a_4_0);

  /* Assume input args are equal: */ 

  /* Begin: Assume globals are equal: */ 
//nondet values for side 0:
  RVT_NONDET_ARRAY(rvs0_a,5);	/* Generated by:  RVMainGen::gen_equal_nondet_globals(621)(626)(392)(254)/ c:\newrvt\rv_temps.cpp:399*/
//alloc for side 1:
//copy leaves from side 0 to 1:
  RVT_COPY_ARRAY(rvs1_a,rvs0_a, 5);	/* Generated by:  RVMainGen::gen_equal_nondet_globals(621)(626)(392)(254)(614)(621)(626)(392)(291)/ c:\newrvt\rv_temps.cpp:368*/
//until here

  /* End: Assume globals are equal: */ 
// for asserting global equality:

  /* run each side's main() */
  retval0 = chk0_main();
  retval1 = chk1_main();
  /* Assertions: */

  /* Compare return values: */ 
  assert( retval0 == retval1 );	/* Generated by:  RVMainGen::gen_main(621)(626)(392)(322)/ c:\newrvt\rv_temps.cpp:352*/

  /* Compare output args: */ 
  RVT_ASSERT_EQ_ARRAY(rvs0_a,rvs1_a,5 );	/* Generated by:  RVMainGen::gen_globals_check_output(621)(626)(392)(316)/ c:\newrvt\rv_temps.cpp:404*/


  return 0;
}
